In [2]:
import pandas as pd
import numpy as np

b1 = pd.read_csv('zillow_1_bed.csv')
b2 = pd.read_csv('zillow_2_bed.csv')
b3 = pd.read_csv('zillow_3_bed.csv')
b4 = pd.read_csv('zillow_4_bed.csv')
b5 = pd.read_csv('zillow_5_bed.csv')

In [3]:
b1.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31
0,9,0,California,State,CA,130666.0,131262.0,132034.0,133738.0,135643.0,...,474558.0,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0
1,54,1,Texas,State,TX,79217.0,79404.0,79462.0,79387.0,79256.0,...,151288.0,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0
2,43,2,New York,State,NY,149865.0,150836.0,151597.0,153131.0,154511.0,...,380515.0,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0
3,14,3,Florida,State,FL,61645.0,61829.0,62003.0,62394.0,62753.0,...,160331.0,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0
4,21,4,Illinois,State,IL,101842.0,102089.0,102587.0,103494.0,104475.0,...,157867.0,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0

In [4]:
b1['Bedrooms'] = 1
b1.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
0,9,0,California,State,CA,130666.0,131262.0,132034.0,133738.0,135643.0,...,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,54,1,Texas,State,TX,79217.0,79404.0,79462.0,79387.0,79256.0,...,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,43,2,New York,State,NY,149865.0,150836.0,151597.0,153131.0,154511.0,...,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,14,3,Florida,State,FL,61645.0,61829.0,62003.0,62394.0,62753.0,...,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,21,4,Illinois,State,IL,101842.0,102089.0,102587.0,103494.0,104475.0,...,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0,1

In [5]:
b2['Bedrooms'] = 2
b3['Bedrooms'] = 3
b4['Bedrooms'] = 4
b5['Bedrooms'] = 5
b5.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
0,9,0,California,State,CA,355256.0,357025.0,359052.0,363466.0,368018.0,...,1165917.0,1176776.0,1188630.0,1202776.0,1223059.0,1245804.0,1273522.0,1299838.0,1320360.0,5
1,54,1,Texas,State,TX,264765.0,264898.0,264864.0,265195.0,265124.0,...,556570.0,566199.0,575189.0,585079.0,596119.0,608501.0,620986.0,635881.0,649709.0,5
2,43,2,New York,State,NY,246709.0,248318.0,249731.0,252551.0,255101.0,...,640749.0,645973.0,650780.0,655664.0,661528.0,668404.0,676934.0,685689.0,694544.0,5
3,14,3,Florida,State,FL,245355.0,246223.0,247190.0,248963.0,250624.0,...,629133.0,644684.0,659833.0,673751.0,688778.0,704022.0,723389.0,745077.0,768272.0,5
4,21,4,Illinois,State,IL,270143.0,270803.0,271786.0,273690.0,275634.0,...,453478.0,457656.0,461969.0,466563.0,470634.0,474824.0,480109.0,486058.0,492748.0,5

In [6]:
df = pd.concat([b1,b2,b3,b4,b5])
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
0,9,0,California,State,CA,130666.0,131262.0,132034.0,133738.0,135643.0,...,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,54,1,Texas,State,TX,79217.0,79404.0,79462.0,79387.0,79256.0,...,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,43,2,New York,State,NY,149865.0,150836.0,151597.0,153131.0,154511.0,...,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,14,3,Florida,State,FL,61645.0,61829.0,62003.0,62394.0,62753.0,...,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,21,4,Illinois,State,IL,101842.0,102089.0,102587.0,103494.0,104475.0,...,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0,1

In [7]:
df.tail()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
46,3,46,Alaska,State,AK,214953.0,215254.0,215687.0,216083.0,216840.0,...,484244.0,487860.0,485651.0,486429.0,487019.0,494481.0,498079.0,508005.0,516605.0,5
47,37,47,North Dakota,State,ND,NaN,NaN,NaN,NaN,NaN,...,372252.0,374766.0,377261.0,380658.0,384404.0,388462.0,391213.0,394193.0,397404.0,5
48,58,48,Vermont,State,VT,169926.0,170215.0,170933.0,172162.0,173635.0,...,423845.0,430009.0,434340.0,440450.0,446707.0,454035.0,460075.0,465369.0,469497.0,5
49,12,49,District of Columbia,State,DC,500641.0,503803.0,508207.0,516084.0,524297.0,...,1602209.0,1619283.0,1631370.0,1645250.0,1655328.0,1675331.0,1690468.0,1705309.0,1716466.0,5
50,62,50,Wyoming,State,WY,NaN,NaN,NaN,NaN,NaN,...,409134.0,412441.0,415577.0,NaN,431719.0,440221.0,443886.0,447650.0,451332.0,5

In [9]:
df.describe()

,RegionID,SizeRank,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
count,255.000000,255.000000,229.000000,229.000000,229.000000,229.000000,230.000000,230.000000,230.000000,230.000000,...,2.550000e+02,2.550000e+02,2.550000e+02,2.490000e+02,2.550000e+02,2.550000e+02,2.550000e+02,2.550000e+02,2.550000e+02,255.000000
mean,33.137255,25.000000,149234.672489,149651.951965,150102.541485,150982.729258,151555.473913,152443.343478,153362.043478,154295.956522,...,3.504593e+05,3.546017e+05,3.584196e+05,3.652814e+05,3.678729e+05,3.735401e+05,3.788361e+05,3.844007e+05,3.892265e+05,3.000000
std,17.123934,14.748549,73317.325142,73666.873122,74027.405225,74738.710937,75489.862781,76175.865468,76836.655601,77562.310925,...,2.130802e+05,2.157279e+05,2.181847e+05,2.221970e+05,2.230940e+05,2.264233e+05,2.300767e+05,2.337870e+05,2.368880e+05,1.416995
min,3.000000,0.000000,30172.000000,30202.000000,30254.000000,30307.000000,30430.000000,30527.000000,30727.000000,30871.000000,...,6.769900e+04,6.818100e+04,6.866600e+04,6.999600e+04,7.121500e+04,7.268300e+04,7.319300e+04,7.393000e+04,7.454900e+04,1.000000
25%,19.000000,12.000000,94182.000000,94251.000000,94439.000000,94777.000000,94726.500000,95075.000000,95408.000000,96135.750000,...,1.935665e+05,1.963485e+05,1.988285e+05,2.021570e+05,2.052840e+05,2.083080e+05,2.115540e+05,2.144415e+05,2.168670e+05,2.000000
50%,34.000000,25.000000,131899.000000,132564.000000,133084.000000,134298.000000,135537.000000,136574.500000,137173.500000,137372.500000,...,3.121360e+05,3.145280e+05,3.167030e+05,3.237010e+05,3.246120e+05,3.291750e+05,3.321630e+05,3.368380e+05,3.410470e+05,3.000000
75%,47.000000,38.000000,189305.000000,190664.000000,191717.000000,192224.000000,192682.000000,193927.750000,194782.000000,195299.000000,...,4.325370e+05,4.368195e+05,4.439530e+05,4.527800e+05,4.548985e+05,4.615390e+05,4.664130e+05,4.724580e+05,4.782340e+05,4.000000
max,62.000000,50.000000,500641.000000,503803.000000,508207.000000,516084.000000,524297.000000,529853.000000,533691.000000,537833.000000,...,1.602209e+06,1.619283e+06,1.631370e+06,1.645250e+06,1.655328e+06,1.675331e+06,1.690468e+06,1.705309e+06,1.716466e+06,5.000000

In [13]:
len(df)

255

In [33]:
df = df.drop(['RegionID', 'SizeRank', 'RegionName', 'RegionType'], axis=1)
df

KeyError: "['RegionID' 'SizeRank' 'RegionName' 'RegionType'] not found in axis"

In [34]:
df

,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,Bedrooms
0,CA,130666.0,131262.0,132034.0,133738.0,135643.0,137697.0,139782.0,141994.0,144212.0,...,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,TX,79217.0,79404.0,79462.0,79387.0,79256.0,78960.0,79271.0,79487.0,79837.0,...,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,NY,149865.0,150836.0,151597.0,153131.0,154511.0,156097.0,157599.0,158773.0,159668.0,...,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,FL,61645.0,61829.0,62003.0,62394.0,62753.0,63152.0,63505.0,63858.0,64227.0,...,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,IL,101842.0,102089.0,102587.0,103494.0,104475.0,105362.0,106244.0,107244.0,108249.0,...,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,AK,214953.0,215254.0,215687.0,216083.0,216840.0,216305.0,216034.0,215255.0,215566.0,...,484244.0,487860.0,485651.0,486429.0,487019.0,494481.0,498079.0,508005.0,516605.0,5
47,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,372252.0,374766.0,377261.0,380658.0,384404.0,388462.0,391213.0,394193.0,397404.0,5
48,VT,169926.0,170215.0,170933.0,172162.0,173635.0,174749.0,175646.0,176389.0,177407.0,...,423845.0,430009.0,434340.0,440450.0,446707.0,454035.0,460075.0,465369.0,469497.0,5
49,DC,500641.0,503803.0,508207.0,516084.0,524297.0,529853.0,533691.0,537833.0,541995.0,...,1602209.0,1619283.0,1631370.0,1645250.0,1655328.0,1675331.0,1690468.0,1705309.0,1716466.0,5
50,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409134.0,412441.0,415577.0,NaN,431719.0,440221.0,443886.0,447650.0,451332.0,5

In [35]:
df.isnull().sum()

StateName      0
2000-01-31    26
2000-02-29    26
2000-03-31    26
2000-04-30    26
              ..
2022-02-28     0
2022-03-31     0
2022-04-30     0
2022-05-31     0
Bedrooms       0
Length: 271, dtype: int64

In [40]:
dates = list(df.columns)
dates.remove('StateName')
dates.remove('Bedrooms')
dates

['2000-01-31',
 '2000-02-29',
 '2000-03-31',
 '2000-04-30',
 '2000-05-31',
 '2000-06-30',
 '2000-07-31',
 '2000-08-31',
 '2000-09-30',
 '2000-10-31',
 '2000-11-30',
 '2000-12-31',
 '2001-01-31',
 '2001-02-28',
 '2001-03-31',
 '2001-04-30',
 '2001-05-31',
 '2001-06-30',
 '2001-07-31',
 '2001-08-31',
 '2001-09-30',
 '2001-10-31',
 '2001-11-30',
 '2001-12-31',
 '2002-01-31',
 '2002-02-28',
 '2002-03-31',
 '2002-04-30',
 '2002-05-31',
 '2002-06-30',
 '2002-07-31',
 '2002-08-31',
 '2002-09-30',
 '2002-10-31',
 '2002-11-30',
 '2002-12-31',
 '2003-01-31',
 '2003-02-28',
 '2003-03-31',
 '2003-04-30',
 '2003-05-31',
 '2003-06-30',
 '2003-07-31',
 '2003-08-31',
 '2003-09-30',
 '2003-10-31',
 '2003-11-30',
 '2003-12-31',
 '2004-01-31',
 '2004-02-29',
 '2004-03-31',
 '2004-04-30',
 '2004-05-31',
 '2004-06-30',
 '2004-07-31',
 '2004-08-31',
 '2004-09-30',
 '2004-10-31',
 '2004-11-30',
 '2004-12-31',
 '2005-01-31',
 '2005-02-28',
 '2005-03-31',
 '2005-04-30',
 '2005-05-31',
 '2005-06-30',
 '2005-07-31',
 '2005-08-31',
 '2005-09-30',
 '2005-10-31',
 '2005-11-30',
 '2005-12-31',
 '2006-01-31',
 '2006-02-28',
 '2006-03-31',
 '2006-04-30',
 '2006-05-31',
 '2006-06-30',
 '2006-07-31',
 '2006-08-31',
 '2006-09-30',
 '2006-10-31',
 '2006-11-30',
 '2006-12-31',
 '2007-01-31',
 '2007-02-28',
 '2007-03-31',
 '2007-04-30',
 '2007-05-31',
 '2007-06-30',
 '2007-07-31',
 '2007-08-31',
 '2007-09-30',
 '2007-10-31',
 '2007-11-30',
 '2007-12-31',
 '2008-01-31',
 '2008-02-29',
 '2008-03-31',
 '2008-04-30',
 '2008-05-31',
 '2008-06-30',
 '2008-07-31',
 '2008-08-31',
 '2008-09-30',
 '2008-10-31',
 '2008-11-30',
 '2008-12-31',
 '2009-01-31',
 '2009-02-28',
 '2009-03-31',
 '2009-04-30',
 '2009-05-31',
 '2009-06-30',
 '2009-07-31',
 '2009-08-31',
 '2009-09-30',
 '2009-10-31',
 '2009-11-30',
 '2009-12-31',
 '2010-01-31',
 '2010-02-28',
 '2010-03-31',
 '2010-04-30',
 '2010-05-31',
 '2010-06-30',
 '2010-07-31',
 '2010-08-31',
 '2010-09-30',
 '2010-10-31',
 '2010-11-30',
 '2010-12-31',
 '2011-01-31',
 '2011-02-28',
 '2011-03-31',
 '2011-04-30',
 '2011-05-31',
 '2011-06-30',
 '2011-07-31',
 '2011-08-31',
 '2011-09-30',
 '2011-10-31',
 '2011-11-30',
 '2011-12-31',
 '2012-01-31',
 '2012-02-29',
 '2012-03-31',
 '2012-04-30',
 '2012-05-31',
 '2012-06-30',
 '2012-07-31',
 '2012-08-31',
 '2012-09-30',
 '2012-10-31',
 '2012-11-30',
 '2012-12-31',
 '2013-01-31',
 '2013-02-28',
 '2013-03-31',
 '2013-04-30',
 '2013-05-31',
 '2013-06-30',
 '2013-07-31',
 '2013-08-31',
 '2013-09-30',
 '2013-10-31',
 '2013-11-30',
 '2013-12-31',
 '2014-01-31',
 '2014-02-28',
 '2014-03-31',
 '2014-04-30',
 '2014-05-31',
 '2014-06-30',
 '2014-07-31',
 '2014-08-31',
 '2014-09-30',
 '2014-10-31',
 '2014-11-30',
 '2014-12-31',
 '2015-01-31',
 '2015-02-28',
 '2015-03-31',
 '2015-04-30',
 '2015-05-31',
 '2015-06-30',
 '2015-07-31',
 '2015-08-31',
 '2015-09-30',
 '2015-10-31',
 '2015-11-30',
 '2015-12-31',
 '2016-01-31',
 '2016-02-29',
 '2016-03-31',
 '2016-04-30',
 '2016-05-31',
 '2016-06-30',
 '2016-07-31',
 '2016-08-31',
 '2016-09-30',
 '2016-10-31',
 '2016-11-30',
 '2016-12-31',
 '2017-01-31',
 '2017-02-28',
 '2017-03-31',
 '2017-04-30',
 '2017-05-31',
 '2017-06-30',
 '2017-07-31',
 '2017-08-31',
 '2017-09-30',
 '2017-10-31',
 '2017-11-30',
 '2017-12-31',
 '2018-01-31',
 '2018-02-28',
 '2018-03-31',
 '2018-04-30',
 '2018-05-31',
 '2018-06-30',
 '2018-07-31',
 '2018-08-31',
 '2018-09-30',
 '2018-10-31',
 '2018-11-30',
 '2018-12-31',
 '2019-01-31',
 '2019-02-28',
 '2019-03-31',
 '2019-04-30',
 '2019-05-31',
 '2019-06-30',
 '2019-07-31',
 '2019-08-31',
 '2019-09-30',
 '2019-10-31',
 '2019-11-30',
 '2019-12-31',
 '2020-01-31',
 '2020-02-29',
 '2020-03-31',
 '2020-04-30',
 '2020-05-31',
 '2020-06-30',
 '2020-07-31',
 '2020-08-31',
 '2020-09-30',
 '2020-10-31',
 '2020-11-30',
 '2020-12-31',
 '2021-01-31',
 '2021-02-28',
 '2021-03-31',
 '2021-04-30',
 '2021-05-31',
 '2021-06-30',
 '2021-07-31',
 '2021-08-31',
 '2021-09-30',
 '2021-10-31',
 '2021-11-30',
 '2021-12-31',
 '2022-01-31',
 '2022-02-28',
 '2022-03-31',
 '2022-04-30',
 '2022-05-31']

In [49]:
new_columns = ['State']
for date in dates:
    date = date[:7]
    new_columns.append(date)
new_columns.append('Bedrooms')
new_columns

['State',
 '2000-01',
 '2000-02',
 '2000-03',
 '2000-04',
 '2000-05',
 '2000-06',
 '2000-07',
 '2000-08',
 '2000-09',
 '2000-10',
 '2000-11',
 '2000-12',
 '2001-01',
 '2001-02',
 '2001-03',
 '2001-04',
 '2001-05',
 '2001-06',
 '2001-07',
 '2001-08',
 '2001-09',
 '2001-10',
 '2001-11',
 '2001-12',
 '2002-01',
 '2002-02',
 '2002-03',
 '2002-04',
 '2002-05',
 '2002-06',
 '2002-07',
 '2002-08',
 '2002-09',
 '2002-10',
 '2002-11',
 '2002-12',
 '2003-01',
 '2003-02',
 '2003-03',
 '2003-04',
 '2003-05',
 '2003-06',
 '2003-07',
 '2003-08',
 '2003-09',
 '2003-10',
 '2003-11',
 '2003-12',
 '2004-01',
 '2004-02',
 '2004-03',
 '2004-04',
 '2004-05',
 '2004-06',
 '2004-07',
 '2004-08',
 '2004-09',
 '2004-10',
 '2004-11',
 '2004-12',
 '2005-01',
 '2005-02',
 '2005-03',
 '2005-04',
 '2005-05',
 '2005-06',
 '2005-07',
 '2005-08',
 '2005-09',
 '2005-10',
 '2005-11',
 '2005-12',
 '2006-01',
 '2006-02',
 '2006-03',
 '2006-04',
 '2006-05',
 '2006-06',
 '2006-07',
 '2006-08',
 '2006-09',
 '2006-10',
 '2006-11',
 '2006-12',
 '2007-01',
 '2007-02',
 '2007-03',
 '2007-04',
 '2007-05',
 '2007-06',
 '2007-07',
 '2007-08',
 '2007-09',
 '2007-10',
 '2007-11',
 '2007-12',
 '2008-01',
 '2008-02',
 '2008-03',
 '2008-04',
 '2008-05',
 '2008-06',
 '2008-07',
 '2008-08',
 '2008-09',
 '2008-10',
 '2008-11',
 '2008-12',
 '2009-01',
 '2009-02',
 '2009-03',
 '2009-04',
 '2009-05',
 '2009-06',
 '2009-07',
 '2009-08',
 '2009-09',
 '2009-10',
 '2009-11',
 '2009-12',
 '2010-01',
 '2010-02',
 '2010-03',
 '2010-04',
 '2010-05',
 '2010-06',
 '2010-07',
 '2010-08',
 '2010-09',
 '2010-10',
 '2010-11',
 '2010-12',
 '2011-01',
 '2011-02',
 '2011-03',
 '2011-04',
 '2011-05',
 '2011-06',
 '2011-07',
 '2011-08',
 '2011-09',
 '2011-10',
 '2011-11',
 '2011-12',
 '2012-01',
 '2012-02',
 '2012-03',
 '2012-04',
 '2012-05',
 '2012-06',
 '2012-07',
 '2012-08',
 '2012-09',
 '2012-10',
 '2012-11',
 '2012-12',
 '2013-01',
 '2013-02',
 '2013-03',
 '2013-04',
 '2013-05',
 '2013-06',
 '2013-07',
 '2013-08',
 '2013-09',
 '2013-10',
 '2013-11',
 '2013-12',
 '2014-01',
 '2014-02',
 '2014-03',
 '2014-04',
 '2014-05',
 '2014-06',
 '2014-07',
 '2014-08',
 '2014-09',
 '2014-10',
 '2014-11',
 '2014-12',
 '2015-01',
 '2015-02',
 '2015-03',
 '2015-04',
 '2015-05',
 '2015-06',
 '2015-07',
 '2015-08',
 '2015-09',
 '2015-10',
 '2015-11',
 '2015-12',
 '2016-01',
 '2016-02',
 '2016-03',
 '2016-04',
 '2016-05',
 '2016-06',
 '2016-07',
 '2016-08',
 '2016-09',
 '2016-10',
 '2016-11',
 '2016-12',
 '2017-01',
 '2017-02',
 '2017-03',
 '2017-04',
 '2017-05',
 '2017-06',
 '2017-07',
 '2017-08',
 '2017-09',
 '2017-10',
 '2017-11',
 '2017-12',
 '2018-01',
 '2018-02',
 '2018-03',
 '2018-04',
 '2018-05',
 '2018-06',
 '2018-07',
 '2018-08',
 '2018-09',
 '2018-10',
 '2018-11',
 '2018-12',
 '2019-01',
 '2019-02',
 '2019-03',
 '2019-04',
 '2019-05',
 '2019-06',
 '2019-07',
 '2019-08',
 '2019-09',
 '2019-10',
 '2019-11',
 '2019-12',
 '2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12',
 '2021-01',
 '2021-02',
 '2021-03',
 '2021-04',
 '2021-05',
 '2021-06',
 '2021-07',
 '2021-08',
 '2021-09',
 '2021-10',
 '2021-11',
 '2021-12',
 '2022-01',
 '2022-02',
 '2022-03',
 '2022-04',
 '2022-05',
 'Bedrooms']

In [50]:
df.set_axis(new_columns, axis=1, inplace=True)
df

,State,2000-01,2000-02,2000-03,2000-04,2000-05,2000-06,2000-07,2000-08,2000-09,...,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,Bedrooms
0,CA,130666.0,131262.0,132034.0,133738.0,135643.0,137697.0,139782.0,141994.0,144212.0,...,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,TX,79217.0,79404.0,79462.0,79387.0,79256.0,78960.0,79271.0,79487.0,79837.0,...,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,NY,149865.0,150836.0,151597.0,153131.0,154511.0,156097.0,157599.0,158773.0,159668.0,...,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,FL,61645.0,61829.0,62003.0,62394.0,62753.0,63152.0,63505.0,63858.0,64227.0,...,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,IL,101842.0,102089.0,102587.0,103494.0,104475.0,105362.0,106244.0,107244.0,108249.0,...,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,AK,214953.0,215254.0,215687.0,216083.0,216840.0,216305.0,216034.0,215255.0,215566.0,...,484244.0,487860.0,485651.0,486429.0,487019.0,494481.0,498079.0,508005.0,516605.0,5
47,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,372252.0,374766.0,377261.0,380658.0,384404.0,388462.0,391213.0,394193.0,397404.0,5
48,VT,169926.0,170215.0,170933.0,172162.0,173635.0,174749.0,175646.0,176389.0,177407.0,...,423845.0,430009.0,434340.0,440450.0,446707.0,454035.0,460075.0,465369.0,469497.0,5
49,DC,500641.0,503803.0,508207.0,516084.0,524297.0,529853.0,533691.0,537833.0,541995.0,...,1602209.0,1619283.0,1631370.0,1645250.0,1655328.0,1675331.0,1690468.0,1705309.0,1716466.0,5
50,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409134.0,412441.0,415577.0,NaN,431719.0,440221.0,443886.0,447650.0,451332.0,5

# Cleaning Nulls

In [57]:
df.reset_index()
df

,State,2000-01,2000-02,2000-03,2000-04,2000-05,2000-06,2000-07,2000-08,2000-09,...,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,Bedrooms
0,CA,130666.0,131262.0,132034.0,133738.0,135643.0,137697.0,139782.0,141994.0,144212.0,...,478763.0,480599.0,483470.0,487631.0,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,TX,79217.0,79404.0,79462.0,79387.0,79256.0,78960.0,79271.0,79487.0,79837.0,...,153565.0,155598.0,157066.0,159203.0,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,NY,149865.0,150836.0,151597.0,153131.0,154511.0,156097.0,157599.0,158773.0,159668.0,...,383446.0,385857.0,388216.0,390318.0,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,FL,61645.0,61829.0,62003.0,62394.0,62753.0,63152.0,63505.0,63858.0,64227.0,...,163656.0,166893.0,170015.0,173024.0,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,IL,101842.0,102089.0,102587.0,103494.0,104475.0,105362.0,106244.0,107244.0,108249.0,...,158823.0,159647.0,160564.0,161564.0,162646.0,163691.0,164843.0,165896.0,167229.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,AK,214953.0,215254.0,215687.0,216083.0,216840.0,216305.0,216034.0,215255.0,215566.0,...,484244.0,487860.0,485651.0,486429.0,487019.0,494481.0,498079.0,508005.0,516605.0,5
47,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,372252.0,374766.0,377261.0,380658.0,384404.0,388462.0,391213.0,394193.0,397404.0,5
48,VT,169926.0,170215.0,170933.0,172162.0,173635.0,174749.0,175646.0,176389.0,177407.0,...,423845.0,430009.0,434340.0,440450.0,446707.0,454035.0,460075.0,465369.0,469497.0,5
49,DC,500641.0,503803.0,508207.0,516084.0,524297.0,529853.0,533691.0,537833.0,541995.0,...,1602209.0,1619283.0,1631370.0,1645250.0,1655328.0,1675331.0,1690468.0,1705309.0,1716466.0,5
50,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409134.0,412441.0,415577.0,NaN,431719.0,440221.0,443886.0,447650.0,451332.0,5

In [62]:
df = df.fillna(df.mean())

In [63]:
df.isnull().sum()

State       0
2000-01     0
2000-02     0
2000-03     0
2000-04     0
           ..
2022-02     0
2022-03     0
2022-04     0
2022-05     0
Bedrooms    0
Length: 271, dtype: int64

# Transpose Data

In [72]:
df = df.reset_index()
df = df.drop('index', axis=1)
df = df.drop('level_0', axis=1)
df

,State,2000-01,2000-02,2000-03,2000-04,2000-05,2000-06,2000-07,2000-08,2000-09,...,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,Bedrooms
0,CA,130666.000000,131262.000000,132034.000000,133738.000000,135643.000000,137697.000000,139782.000000,141994.000000,144212.000000,...,478763.0,480599.0,483470.0,4.876310e+05,493892.0,501094.0,510219.0,518854.0,525553.0,1
1,TX,79217.000000,79404.000000,79462.000000,79387.000000,79256.000000,78960.000000,79271.000000,79487.000000,79837.000000,...,153565.0,155598.0,157066.0,1.592030e+05,161747.0,164703.0,167546.0,170630.0,173599.0,1
2,NY,149865.000000,150836.000000,151597.000000,153131.000000,154511.000000,156097.000000,157599.000000,158773.000000,159668.000000,...,383446.0,385857.0,388216.0,3.903180e+05,392702.0,395211.0,398735.0,402448.0,406362.0,1
3,FL,61645.000000,61829.000000,62003.000000,62394.000000,62753.000000,63152.000000,63505.000000,63858.000000,64227.000000,...,163656.0,166893.0,170015.0,1.730240e+05,176592.0,180200.0,184810.0,189743.0,195474.0,1
4,IL,101842.000000,102089.000000,102587.000000,103494.000000,104475.000000,105362.000000,106244.000000,107244.000000,108249.000000,...,158823.0,159647.0,160564.0,1.615640e+05,162646.0,163691.0,164843.0,165896.0,167229.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,AK,214953.000000,215254.000000,215687.000000,216083.000000,216840.000000,216305.000000,216034.000000,215255.000000,215566.000000,...,484244.0,487860.0,485651.0,4.864290e+05,487019.0,494481.0,498079.0,508005.0,516605.0,5
251,ND,149234.672489,149651.951965,150102.541485,150982.729258,151555.473913,152443.343478,153362.043478,154295.956522,155257.404348,...,372252.0,374766.0,377261.0,3.806580e+05,384404.0,388462.0,391213.0,394193.0,397404.0,5
252,VT,169926.000000,170215.000000,170933.000000,172162.000000,173635.000000,174749.000000,175646.000000,176389.000000,177407.000000,...,423845.0,430009.0,434340.0,4.404500e+05,446707.0,454035.0,460075.0,465369.0,469497.0,5
253,DC,500641.000000,503803.000000,508207.000000,516084.000000,524297.000000,529853.000000,533691.000000,537833.000000,541995.000000,...,1602209.0,1619283.0,1631370.0,1.645250e+06,1655328.0,1675331.0,1690468.0,1705309.0,1716466.0,5
254,WY,149234.672489,149651.951965,150102.541485,150982.729258,151555.473913,152443.343478,153362.043478,154295.956522,155257.404348,...,409134.0,412441.0,415577.0,3.652814e+05,431719.0,440221.0,443886.0,447650.0,451332.0,5

In [79]:
df2 = pd.DataFrame(columns=['State', 'Time', 'Price', 'Bedrooms'])
df2
print(df['2000-02'].name)
# for column in df:
#     print(column)
for i in df.index:
    print(i)

2000-02
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254

In [82]:
for i in df.index:
    for column in df:
        if column != 'State' and column != 'Bedrooms':
            df2 = df2.append({'State': df['State'][i], 'Time': df[column].name, 'Price': df[column][i], 'Bedrooms': df['Bedrooms'][i]}, ignore_index=True)
df2

       State     Time     Price Bedrooms
0         CA  2000-01  130666.0        1
1         CA  2000-02  131262.0        1
2         CA  2000-03  132034.0        1
3         CA  2000-04  133738.0        1
4         CA  2000-05  135643.0        1
...      ...      ...       ...      ...
162171    WY  2022-01  431719.0        5
162172    WY  2022-02  440221.0        5
162173    WY  2022-03  443886.0        5
162174    WY  2022-04  447650.0        5
162175    WY  2022-05  451332.0        5

[162176 rows x 4 columns]

In [89]:
def to_int(date):
    dates = date.split('-')
    year = int(dates[0])
    month = int(dates[1])
    date_in_months = year * 12 + month
    start_date = 2000 * 12
    result = date_in_months - start_date
    return result
to_int('2000-01')

1

In [90]:
for i in df2.index:
    df2['Time'][i] = to_int(df2['Time'][i])
df2

<ipython-input-90-6d585066f794>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Time'][i] = to_int(df2['Time'][i])

       State Time     Price Bedrooms
0         CA    1  130666.0        1
1         CA    2  131262.0        1
2         CA    3  132034.0        1
3         CA    4  133738.0        1
4         CA    5  135643.0        1
...      ...  ...       ...      ...
162171    WY  265  431719.0        5
162172    WY  266  440221.0        5
162173    WY  267  443886.0        5
162174    WY  268  447650.0        5
162175    WY  269  451332.0        5

[162176 rows x 4 columns]

In [93]:
dataset = []

for i in df2.index:
    dataset.append(df2.loc[i].values.tolist())

dataset

[['CA', 1, 130666.0, 1],
 ['CA', 2, 131262.0, 1],
 ['CA', 3, 132034.0, 1],
 ['CA', 4, 133738.0, 1],
 ['CA', 5, 135643.0, 1],
 ['CA', 6, 137697.0, 1],
 ['CA', 7, 139782.0, 1],
 ['CA', 8, 141994.0, 1],
 ['CA', 9, 144212.0, 1],
 ['CA', 10, 146304.0, 1],
 ['CA', 11, 148353.0, 1],
 ['CA', 12, 150391.0, 1],
 ['CA', 13, 152079.0, 1],
 ['CA', 14, 153868.0, 1],
 ['CA', 15, 155928.0, 1],
 ['CA', 16, 158424.0, 1],
 ['CA', 17, 160714.0, 1],
 ['CA', 18, 162704.0, 1],
 ['CA', 19, 164631.0, 1],
 ['CA', 20, 166603.0, 1],
 ['CA', 21, 168431.0, 1],
 ['CA', 22, 170128.0, 1],
 ['CA', 23, 171705.0, 1],
 ['CA', 24, 173142.0, 1],
 ['CA', 25, 174344.0, 1],
 ['CA', 26, 175640.0, 1],
 ['CA', 27, 177241.0, 1],
 ['CA', 28, 179312.0, 1],
 ['CA', 29, 181614.0, 1],
 ['CA', 30, 184119.0, 1],
 ['CA', 31, 187082.0, 1],
 ['CA', 32, 190201.0, 1],
 ['CA', 33, 193263.0, 1],
 ['CA', 34, 196075.0, 1],
 ['CA', 35, 198869.0, 1],
 ['CA', 36, 201715.0, 1],
 ['CA', 37, 204124.0, 1],
 ['CA', 38, 206381.0, 1],
 ['CA', 39, 208869.0, 1],
 ['CA', 40, 211691.0, 1],
 ['CA', 41, 214729.0, 1],
 ['CA', 42, 217272.0, 1],
 ['CA', 43, 220254.0, 1],
 ['CA', 44, 223411.0, 1],
 ['CA', 45, 226923.0, 1],
 ['CA', 46, 230104.0, 1],
 ['CA', 47, 233209.0, 1],
 ['CA', 48, 236203.0, 1],
 ['CA', 49, 239746.0, 1],
 ['CA', 50, 243813.0, 1],
 ['CA', 51, 248495.0, 1],
 ['CA', 52, 253490.0, 1],
 ['CA', 53, 259276.0, 1],
 ['CA', 54, 265740.0, 1],
 ['CA', 55, 272035.0, 1],
 ['CA', 56, 277665.0, 1],
 ['CA', 57, 282896.0, 1],
 ['CA', 58, 288025.0, 1],
 ['CA', 59, 292408.0, 1],
 ['CA', 60, 296945.0, 1],
 ['CA', 61, 300921.0, 1],
 ['CA', 62, 305457.0, 1],
 ['CA', 63, 310271.0, 1],
 ['CA', 64, 315769.0, 1],
 ['CA', 65, 320979.0, 1],
 ['CA', 66, 325538.0, 1],
 ['CA', 67, 329939.0, 1],
 ['CA', 68, 334524.0, 1],
 ['CA', 69, 338938.0, 1],
 ['CA', 70, 343312.0, 1],
 ['CA', 71, 346475.0, 1],
 ['CA', 72, 349550.0, 1],
 ['CA', 73, 352081.0, 1],
 ['CA', 74, 354487.0, 1],
 ['CA', 75, 356691.0, 1],
 ['CA', 76, 358422.0, 1],
 ['CA', 77, 360133.0, 1],
 ['CA', 78, 361026.0, 1],
 ['CA', 79, 360894.0, 1],
 ['CA', 80, 360482.0, 1],
 ['CA', 81, 359103.0, 1],
 ['CA', 82, 358162.0, 1],
 ['CA', 83, 357112.0, 1],
 ['CA', 84, 356490.0, 1],
 ['CA', 85, 356124.0, 1],
 ['CA', 86, 355586.0, 1],
 ['CA', 87, 354637.0, 1],
 ['CA', 88, 353212.0, 1],
 ['CA', 89, 350882.0, 1],
 ['CA', 90, 348425.0, 1],
 ['CA', 91, 345180.0, 1],
 ['CA', 92, 342072.0, 1],
 ['CA', 93, 338515.0, 1],
 ['CA', 94, 334662.0, 1],
 ['CA', 95, 331214.0, 1],
 ['CA', 96, 327157.0, 1],
 ['CA', 97, 323655.0, 1],
 ['CA', 98, 319064.0, 1],
 ['CA', 99, 313719.0, 1],
 ['CA', 100, 307614.0, 1],
 ['CA', 101, 301029.0, 1],
 ['CA', 102, 295113.0, 1],
 ['CA', 103, 288829.0, 1],
 ['CA', 104, 283002.0, 1],
 ['CA', 105, 277239.0, 1],
 ['CA', 106, 271753.0, 1],
 ['CA', 107, 265721.0, 1],
 ['CA', 108, 259991.0, 1],
 ['CA', 109, 255011.0, 1],
 ['CA', 110, 251742.0, 1],
 ['CA', 111, 248435.0, 1],
 ['CA', 112, 244487.0, 1],
 ['CA', 113, 240709.0, 1],
 ['CA', 114, 236902.0, 1],
 ['CA', 115, 234089.0, 1],
 ['CA', 116, 231488.0, 1],
 ['CA', 117, 229853.0, 1],
 ['CA', 118, 228985.0, 1],
 ['CA', 119, 229426.0, 1],
 ['CA', 120, 230888.0, 1],
 ['CA', 121, 231305.0, 1],
 ['CA', 122, 230685.0, 1],
 ['CA', 123, 230107.0, 1],
 ['CA', 124, 230207.0, 1],
 ['CA', 125, 230248.0, 1],
 ['CA', 126, 228532.0, 1],
 ['CA', 127, 226233.0, 1],
 ['CA', 128, 223494.0, 1],
 ['CA', 129, 221063.0, 1],
 ['CA', 130, 218644.0, 1],
 ['CA', 131, 216246.0, 1],
 ['CA', 132, 214557.0, 1],
 ['CA', 133, 213035.0, 1],
 ['CA', 134, 211867.0, 1],
 ['CA', 135, 210195.0, 1],
 ['CA', 136, 208474.0, 1],
 ['CA', 137, 205885.0, 1],
 ['CA', 138, 204175.0, 1],
 ['CA', 139, 202649.0, 1],
 ['CA', 140, 200740.0, 1],
 ['CA', 141, 198535.0, 1],
 ['CA', 142, 196427.0, 1],
 ['CA', 143, 195827.0, 1],
 ['CA', 144, 195302.0, 1],
 ['CA', 145, 194891.0, 1],
 ['CA', 146, 194445.0, 1],
 ['CA', 147, 194303.0, 1],
 ['CA', 148, 194787.0, 1],
 ['CA', 149, 195871.0, 1],
 ['CA', 150, 197371.0, 1],
 ['CA', 151, 198978.0, 1],
 ['CA', 152, 200607.0, 1],
 ['CA', 153, 202356.0, 1],
 ['CA', 154, 204888.0, 1],
 ['CA', 155, 207873.0, 1],
 ['CA', 156, 211873.0, 1],
 ['CA', 157, 216120.0, 1],
 ['CA', 158, 220780.0, 1],
 ['CA', 159, 225870.0, 1],
 ['CA', 160, 231461.0, 1],
 ['CA', 161, 237234.0, 1],
 ['CA', 162, 243201.0, 1],
 ['CA', 163, 248757.0, 1],
 ['CA', 164, 254066.0, 1],
 ['CA', 165, 258691.0, 1],
 ['CA', 166, 262863.0, 1],
 ['CA', 167, 266997.0, 1],
 ['CA', 168, 270901.0, 1],
 ['CA', 169, 274738.0, 1],
 ['CA', 170, 278193.0, 1],
 ['CA', 171, 280231.0, 1],
 ['CA', 172, 281509.0, 1],
 ['CA', 173, 282185.0, 1],
 ['CA', 174, 282985.0, 1],
 ['CA', 175, 283806.0, 1],
 ['CA', 176, 283648.0, 1],
 ['CA', 177, 284148.0, 1],
 ['CA', 178, 285261.0, 1],
 ['CA', 179, 287748.0, 1],
 ['CA', 180, 290001.0, 1],
 ['CA', 181, 292077.0, 1],
 ['CA', 182, 294230.0, 1],
 ['CA', 183, 296897.0, 1],
 ['CA', 184, 298971.0, 1],
 ['CA', 185, 301161.0, 1],
 ['CA', 186, 302746.0, 1],
 ['CA', 187, 303568.0, 1],
 ['CA', 188, 304793.0, 1],
 ['CA', 189, 306783.0, 1],
 ['CA', 190, 310004.0, 1],
 ['CA', 191, 312668.0, 1],
 ['CA', 192, 316050.0, 1],
 ['CA', 193, 319429.0, 1],
 ['CA', 194, 322472.0, 1],
 ['CA', 195, 324006.0, 1],
 ['CA', 196, 325831.0, 1],
 ['CA', 197, 327507.0, 1],
 ['CA', 198, 329483.0, 1],
 ['CA', 199, 329927.0, 1],
 ['CA', 200, 331256.0, 1],
 ['CA', 201, 332721.0, 1],
 ['CA', 202, 335865.0, 1],
 ['CA', 203, 338422.0, 1],
 ['CA', 204, 340570.0, 1],
 ['CA', 205, 342790.0, 1],
 ['CA', 206, 344974.0, 1],
 ['CA', 207, 347385.0, 1],
 ['CA', 208, 349299.0, 1],
 ['CA', 209, 351767.0, 1],
 ['CA', 210, 354584.0, 1],
 ['CA', 211, 356140.0, 1],
 ['CA', 212, 357715.0, 1],
 ['CA', 213, 359848.0, 1],
 ['CA', 214, 363372.0, 1],
 ['CA', 215, 367175.0, 1],
 ['CA', 216, 370750.0, 1],
 ['CA', 217, 374694.0, 1],
 ['CA', 218, 378774.0, 1],
 ['CA', 219, 382552.0, 1],
 ['CA', 220, 385701.0, 1],
 ['CA', 221, 388141.0, 1],
 ['CA', 222, 390685.0, 1],
 ['CA', 223, 392075.0, 1],
 ['CA', 224, 393482.0, 1],
 ['CA', 225, 394213.0, 1],
 ['CA', 226, 395853.0, 1],
 ['CA', 227, 396758.0, 1],
 ['CA', 228, 396507.0, 1],
 ['CA', 229, 395789.0, 1],
 ['CA', 230, 395068.0, 1],
 ['CA', 231, 394791.0, 1],
 ['CA', 232, 395127.0, 1],
 ['CA', 233, 395495.0, 1],
 ['CA', 234, 395922.0, 1],
 ['CA', 235, 395532.0, 1],
 ['CA', 236, 395472.0, 1],
 ['CA', 237, 395952.0, 1],
 ['CA', 238, 397162.0, 1],
 ['CA', 239, 398034.0, 1],
 ['CA', 240, 399372.0, 1],
 ['CA', 241, 401491.0, 1],
 ['CA', 242, 404459.0, 1],
 ['CA', 243, 407536.0, 1],
 ['CA', 244, 409356.0, 1],
 ['CA', 245, 408019.0, 1],
 ['CA', 246, 406206.0, 1],
 ['CA', 247, 406824.0, 1],
 ['CA', 248, 410979.0, 1],
 ['CA', 249, 415552.0, 1],
 ['CA', 250, 419633.0, 1],
 ['CA', 251, 423086.0, 1],
 ['CA', 252, 426065.0, 1],
 ['CA', 253, 428636.0, 1],
 ['CA', 254, 431844.0, 1],
 ['CA', 255, 435629.0, 1],
 ['CA', 256, 440640.0, 1],
 ['CA', 257, 448266.0, 1],
 ['CA', 258, 457786.0, 1],
 ['CA', 259, 467937.0, 1],
 ['CA', 260, 474558.0, 1],
 ['CA', 261, 478763.0, 1],
 ['CA', 262, 480599.0, 1],
 ['CA', 263, 483470.0, 1],
 ['CA', 264, 487631.0, 1],
 ['CA', 265, 493892.0, 1],
 ['CA', 266, 501094.0, 1],
 ['CA', 267, 510219.0, 1],
 ['CA', 268, 518854.0, 1],
 ['CA', 269, 525553.0, 1],
 ['TX', 1, 79217.0, 1],
 ['TX', 2, 79404.0, 1],
 ['TX', 3, 79462.0, 1],
 ['TX', 4, 79387.0, 1],
 ['TX', 5, 79256.0, 1],
 ['TX', 6, 78960.0, 1],
 ['TX', 7, 79271.0, 1],
 ['TX', 8, 79487.0, 1],
 ['TX', 9, 79837.0, 1],
 ['TX', 10, 79867.0, 1],
 ['TX', 11, 80180.0, 1],
 ['TX', 12, 80665.0, 1],
 ['TX', 13, 81011.0, 1],
 ['TX', 14, 80965.0, 1],
 ['TX', 15, 80694.0, 1],
 ['TX', 16, 80655.0, 1],
 ['TX', 17, 80624.0, 1],
 ['TX', 18, 80625.0, 1],
 ['TX', 19, 80393.0, 1],
 ['TX', 20, 80253.0, 1],
 ['TX', 21, 80145.0, 1],
 ['TX', 22, 80347.0, 1],
 ['TX', 23, 80209.0, 1],
 ['TX', 24, 80177.0, 1],
 ['TX', 25, 79638.0, 1],
 ['TX', 26, 79674.0, 1],
 ['TX', 27, 79301.0, 1],
 ['TX', 28, 79544.0, 1],
 ['TX', 29, 79562.0, 1],
 ['TX', 30, 80006.0, 1],
 ['TX', 31, 80373.0, 1],
 ['TX', 32, 80705.0, 1],
 ['TX', 33, 80797.0, 1],
 ['TX', 34, 80689.0, 1],
 ['TX', 35, 81055.0, 1],
 ['TX', 36, 81134.0, 1],
 ['TX', 37, 81408.0, 1],
 ['TX', 38, 81259.0, 1],
 ['TX', 39, 81707.0, 1],
 ['TX', 40, 81352.0, 1],
 ['TX', 41, 80891.0, 1],
 ['TX', 42, 80433.0, 1],
 ['TX', 43, 80014.0, 1],
 ['TX', 44, 80105.0, 1],
 ['TX', 45, 79948.0, 1],
 ['TX', 46, 79957.0, 1],
 ['TX', 47, 79801.0, 1],
 ['TX', 48, 79961.0, 1],
 ['TX', 49, 80586.0, 1],
 ['TX', 50, 80821.0, 1],
 ['TX', 51, 81635.0, 1],
 ['TX', 52, 82065.0, 1],
 ['TX', 53, 83022.0, 1],
 ['TX', 54, 82927.0, 1],
 ['TX', 55, 82832.0, 1],
 ['TX', 56, 82835.0, 1],
 ['TX', 57, 83068.0, 1],
 ['TX', 58, 83397.0, 1],
 ['TX', 59, 83072.0, 1],
 ['TX', 60, 83123.0, 1],
 ['TX', 61, 83594.0, 1],
 ['TX', 62, 83973.0, 1],
 ['TX', 63, 84235.0, 1],
 ['TX', 64, 84142.0, 1],
 ['TX', 65, 84416.0, 1],
 ['TX', 66, 83974.0, 1],
 ['TX', 67, 83873.0, 1],
 ['TX', 68, 83794.0, 1],
 ['TX', 69, 84368.0, 1],
 ['TX', 70, 84333.0, 1],
 ['TX', 71, 84369.0, 1],
 ['TX', 72, 84491.0, 1],
 ['TX', 73, 84902.0, 1],
 ['TX', 74, 85208.0, 1],
 ['TX', 75, 84977.0, 1],
 ['TX', 76, 85023.0, 1],
 ['TX', 77, 85423.0, 1],
 ['TX', 78, 85779.0, 1],
 ['TX', 79, 85977.0, 1],
 ['TX', 80, 85646.0, 1],
 ['TX', 81, 86203.0, 1],
 ['TX', 82, 86199.0, 1],
 ['TX', 83, 86524.0, 1],
 ['TX', 84, 86179.0, 1],
 ['TX', 85, 86303.0, 1],
 ['TX', 86, 85826.0, 1],
 ['TX', 87, 85494.0, 1],
 ['TX', 88, 85840.0, 1],
 ['TX', 89, 86363.0, 1],
 ['TX', 90, 86546.0, 1],
 ['TX', 91, 86392.0, 1],
 ['TX', 92, 86144.0, 1],
 ['TX', 93, 86388.0, 1],
 ['TX', 94, 86112.0, 1],
 ['TX', 95, 86330.0, 1],
 ['TX', 96, 85844.0, 1],
 ['TX', 97, 85404.0, 1],
 ['TX', 98, 84734.0, 1],
 ['TX', 99, 84481.0, 1],
 ['TX', 100, 84439.0, 1],
 ['TX', 101, 84378.0, 1],
 ['TX', 102, 84418.0, 1],
 ['TX', 103, 84260.0, 1],
 ['TX', 104, 83934.0, 1],
 ['TX', 105, 83457.0, 1],
 ['TX', 106, 82990.0, 1],
 ['TX', 107, 82209.0, 1],
 ['TX', 108, 81675.0, 1],
 ['TX', 109, 80910.0, 1],
 ['TX', 110, 80810.0, 1],
 ['TX', 111, 80486.0, 1],
 ['TX', 112, 80605.0, 1],
 ['TX', 113, 80555.0, 1],
 ['TX', 114, 80581.0, 1],
 ['TX', 115, 80495.0, 1],
 ['TX', 116, 80156.0, 1],
 ['TX', 117, 79795.0, 1],
 ['TX', 118, 79397.0, 1],
 ['TX', 119, 79255.0, 1],
 ['TX', 120, 79202.0, 1],
 ['TX', 121, 78914.0, 1],
 ['TX', 122, 78667.0, 1],
 ['TX', 123, 78269.0, 1],
 ['TX', 124, 78173.0, 1],
 ['TX', 125, 78077.0, 1],
 ['TX', 126, 77980.0, 1],
 ['TX', 127, 77614.0, 1],
 ['TX', 128, 77228.0, 1],
 ['TX', 129, 76808.0, 1],
 ['TX', 130, 76558.0, 1],
 ['TX', 131, 76119.0, 1],
 ['TX', 132, 75806.0, 1],
 ['TX', 133, 75214.0, 1],
 ['TX', 134, 74771.0, 1],
 ['TX', 135, 74098.0, 1],
 ['TX', 136, 73775.0, 1],
 ['TX', 137, 73437.0, 1],
 ['TX', 138, 73395.0, 1],
 ['TX', 139, 73413.0, 1],
 ['TX', 140, 73553.0, 1],
 ['TX', 141, 73575.0, 1],
 ['TX', 142, 73652.0, 1],
 ['TX', 143, 73521.0, 1],
 ['TX', 144, 73449.0, 1],
 ['TX', 145, 73149.0, 1],
 ['TX', 146, 73210.0, 1],
 ['TX', 147, 73230.0, 1],
 ['TX', 148, 73311.0, 1],
 ['TX', 149, 73295.0, 1],
 ['TX', 150, 73645.0, 1],
 ['TX', 151, 74147.0, 1],
 ['TX', 152, 74504.0, 1],
 ['TX', 153, 74552.0, 1],
 ['TX', 154, 74710.0, 1],
 ['TX', 155, 74915.0, 1],
 ['TX', 156, 75282.0, 1],
 ['TX', 157, 75543.0, 1],
 ['TX', 158, 76057.0, 1],
 ['TX', 159, 76617.0, 1],
 ['TX', 160, 77344.0, 1],
 ['TX', 161, 77926.0, 1],
 ['TX', 162, 78529.0, 1],
 ['TX', 163, 79121.0, 1],
 ['TX', 164, 79788.0, 1],
 ['TX', 165, 80373.0, 1],
 ['TX', 166, 81034.0, 1],
 ['TX', 167, 81584.0, 1],
 ['TX', 168, 82120.0, 1],
 ['TX', 169, 82598.0, 1],
 ['TX', 170, 83253.0, 1],
 ['TX', 171, 83747.0, 1],
 ['TX', 172, 84158.0, 1],
 ['TX', 173, 84475.0, 1],
 ['TX', 174, 85224.0, 1],
 ['TX', 175, 85797.0, 1],
 ['TX', 176, 86480.0, 1],
 ['TX', 177, 86819.0, 1],
 ['TX', 178, 87446.0, 1],
 ['TX', 179, 88091.0, 1],
 ['TX', 180, 88999.0, 1],
 ['TX', 181, 89689.0, 1],
 ['TX', 182, 90330.0, 1],
 ['TX', 183, 90892.0, 1],
 ['TX', 184, 91398.0, 1],
 ['TX', 185, 91927.0, 1],
 ['TX', 186, 92460.0, 1],
 ['TX', 187, 93055.0, 1],
 ['TX', 188, 93540.0, 1],
 ['TX', 189, 93934.0, 1],
 ['TX', 190, 94631.0, 1],
 ['TX', 191, 95148.0, 1],
 ['TX', 192, 95813.0, 1],
 ['TX', 193, 96234.0, 1],
 ['TX', 194, 96895.0, 1],
 ['TX', 195, 97478.0, 1],
 ['TX', 196, 98115.0, 1],
 ['TX', 197, 98794.0, 1],
 ['TX', 198, 99550.0, 1],
 ['TX', 199, 100478.0, 1],
 ['TX', 200, 100991.0, 1],
 ['TX', 201, 101441.0, 1],
 ['TX', 202, 101978.0, 1],
 ['TX', 203, 103103.0, 1],
 ['TX', 204, 104394.0, 1],
 ['TX', 205, 105347.0, 1],
 ['TX', 206, 106074.0, 1],
 ['TX', 207, 106603.0, 1],
 ['TX', 208, 107163.0, 1],
 ['TX', 209, 107704.0, 1],
 ['TX', 210, 108292.0, 1],
 ['TX', 211, 108953.0, 1],
 ['TX', 212, 109450.0, 1],
 ['TX', 213, 109841.0, 1],
 ['TX', 214, 110258.0, 1],
 ['TX', 215, 110975.0, 1],
 ['TX', 216, 111821.0, 1],
 ['TX', 217, 112774.0, 1],
 ['TX', 218, 113646.0, 1],
 ['TX', 219, 114461.0, 1],
 ['TX', 220, 115273.0, 1],
 ['TX', 221, 116000.0, 1],
 ['TX', 222, 116730.0, 1],
 ['TX', 223, 117336.0, 1],
 ['TX', 224, 118133.0, 1],
 ['TX', 225, 118762.0, 1],
 ['TX', 226, 119364.0, 1],
 ['TX', 227, 119853.0, 1],
 ['TX', 228, 120573.0, 1],
 ['TX', 229, 121629.0, 1],
 ['TX', 230, 122650.0, 1],
 ['TX', 231, 123296.0, 1],
 ['TX', 232, 123614.0, 1],
 ['TX', 233, 123790.0, 1],
 ['TX', 234, 124146.0, 1],
 ['TX', 235, 124531.0, 1],
 ['TX', 236, 125210.0, 1],
 ['TX', 237, 126118.0, 1],
 ['TX', 238, 126525.0, 1],
 ['TX', 239, 126689.0, 1],
 ['TX', 240, 126372.0, 1],
 ['TX', 241, 126895.0, 1],
 ['TX', 242, 127364.0, 1],
 ['TX', 243, 128164.0, 1],
 ['TX', 244, 128433.0, 1],
 ['TX', 245, 128767.0, 1],
 ['TX', 246, 128949.0, 1],
 ['TX', 247, 129218.0, 1],
 ['TX', 248, 129811.0, 1],
 ['TX', 249, 131283.0, 1],
 ['TX', 250, 133019.0, 1],
 ['TX', 251, 134795.0, 1],
 ['TX', 252, 135905.0, 1],
 ['TX', 253, 137237.0, 1],
 ['TX', 254, 138576.0, 1],
 ['TX', 255, 139763.0, 1],
 ['TX', 256, 141278.0, 1],
 ['TX', 257, 143013.0, 1],
 ['TX', 258, 145792.0, 1],
 ['TX', 259, 148331.0, 1],
 ['TX', 260, 151288.0, 1],
 ['TX', 261, 153565.0, 1],
 ['TX', 262, 155598.0, 1],
 ['TX', 263, 157066.0, 1],
 ['TX', 264, 159203.0, 1],
 ['TX', 265, 161747.0, 1],
 ['TX', 266, 164703.0, 1],
 ['TX', 267, 167546.0, 1],
 ['TX', 268, 170630.0, 1],
 ['TX', 269, 173599.0, 1],
 ['NY', 1, 149865.0, 1],
 ['NY', 2, 150836.0, 1],
 ['NY', 3, 151597.0, 1],
 ['NY', 4, 153131.0, 1],
 ['NY', 5, 154511.0, 1],
 ['NY', 6, 156097.0, 1],
 ['NY', 7, 157599.0, 1],
 ['NY', 8, 158773.0, 1],
 ['NY', 9, 159668.0, 1],
 ['NY', 10, 160657.0, 1],
 ['NY', 11, 162105.0, 1],
 ['NY', 12, 163673.0, 1],
 ['NY', 13, 165247.0, 1],
 ['NY', 14, 166597.0, 1],
 ['NY', 15, 168113.0, 1],
 ['NY', 16, 169609.0, 1],
 ['NY', 17, 171164.0, 1],
 ['NY', 18, 172552.0, 1],
 ['NY', 19, 173916.0, 1],
 ['NY', 20, 175445.0, 1],
 ['NY', 21, 177064.0, 1],
 ['NY', 22, 178746.0, 1],
 ['NY', 23, 180347.0, 1],
 ['NY', 24, 181802.0, 1],
 ['NY', 25, 183472.0, 1],
 ['NY', 26, 184815.0, 1],
 ['NY', 27, 186108.0, 1],
 ['NY', 28, 187315.0, 1],
 ['NY', 29, 188799.0, 1],
 ['NY', 30, 190431.0, 1],
 ['NY', 31, 192007.0, 1],
 ['NY', 32, 193752.0, 1],
 ['NY', 33, 195534.0, 1],
 ['NY', 34, 197267.0, 1],
 ['NY', 35, 199017.0, 1],
 ['NY', 36, 200838.0, 1],
 ['NY', 37, 202886.0, 1],
 ['NY', 38, 204961.0, 1],
 ['NY', 39, 207494.0, 1],
 ['NY', 40, 209552.0, 1],
 ['NY', 41, 211848.0, 1],
 ['NY', 42, 214336.0, 1],
 ['NY', 43, 217077.0, 1],
 ['NY', 44, 219904.0, 1],
 ['NY', 45, 222178.0, 1],
 ['NY', 46, 224588.0, 1],
 ['NY', 47, 226471.0, 1],
 ['NY', 48, 228381.0, 1],
 ['NY', 49, 230369.0, 1],
 ['NY', 50, 232363.0, 1],
 ['NY', 51, 234281.0, 1],
 ['NY', 52, 236276.0, 1],
 ['NY', 53, 238749.0, 1],
 ['NY', 54, 241592.0, 1],
 ['NY', 55, 244639.0, 1],
 ['NY', 56, 247537.0, 1],
 ['NY', 57, 250793.0, 1],
 ['NY', 58, 253952.0, 1],
 ['NY', 59, 257222.0, 1],
 ['NY', 60, 260152.0, 1],
 ['NY', 61, 263301.0, 1],
 ['NY', 62, 266414.0, 1],
 ['NY', 63, 269567.0, 1],
 ['NY', 64, 272776.0, 1],
 ['NY', 65, 276104.0, 1],
 ['NY', 66, 279216.0, 1],
 ['NY', 67, 282263.0, 1],
 ['NY', 68, 285559.0, 1],
 ['NY', 69, 288790.0, 1],
 ['NY', 70, 292469.0, 1],
 ['NY', 71, 295736.0, 1],
 ['NY', 72, 299356.0, 1],
 ['NY', 73, 302448.0, 1],
 ['NY', 74, 305077.0, 1],
 ['NY', 75, 306876.0, 1],
 ['NY', 76, 308288.0, 1],
 ['NY', 77, 309948.0, 1],
 ['NY', 78, 311478.0, 1],
 ['NY', 79, 312466.0, 1],
 ['NY', 80, 312731.0, 1],
 ['NY', 81, 312709.0, 1],
 ['NY', 82, 312443.0, 1],
 ['NY', 83, 312281.0, 1],
 ['NY', 84, 312489.0, 1],
 ['NY', 85, 312345.0, 1],
 ['NY', 86, 312318.0, 1],
 ['NY', 87, 312643.0, 1],
 ['NY', 88, 313180.0, 1],
 ['NY', 89, 313874.0, 1],
 ['NY', 90, 313566.0, 1],
 ['NY', 91, 313241.0, 1],
 ['NY', 92, 312944.0, 1],
 ['NY', 93, 313061.0, 1],
 ['NY', 94, 313678.0, 1],
 ['NY', 95, 314015.0, 1],
 ['NY', 96, 313998.0, 1],
 ['NY', 97, 313971.0, 1],
 ['NY', 98, 313732.0, 1],
 ['NY', 99, 313499.0, 1],
 ['NY', 100, 313035.0, 1],
 ['NY', 101, 312201.0, 1],
 ['NY', 102, 311051.0, 1],
 ['NY', 103, 309579.0, 1],
 ['NY', 104, 308502.0, 1],
 ['NY', 105, 307319.0, 1],
 ['NY', 106, 305737.0, 1],
 ['NY', 107, 303467.0, 1],
 ['NY', 108, 300601.0, 1],
 ['NY', 109, 296506.0, 1],
 ['NY', 110, 292729.0, 1],
 ['NY', 111, 289571.0, 1],
 ['NY', 112, 287146.0, 1],
 ['NY', 113, 285431.0, 1],
 ['NY', 114, 283252.0, 1],
 ['NY', 115, 281379.0, 1],
 ['NY', 116, 278718.0, 1],
 ['NY', 117, 277014.0, 1],
 ['NY', 118, 276291.0, 1],
 ['NY', 119, 276011.0, 1],
 ['NY', 120, 275230.0, 1],
 ['NY', 121, 275091.0, 1],
 ['NY', 122, 275582.0, 1],
 ['NY', 123, 275899.0, 1],
 ['NY', 124, 276170.0, 1],
 ['NY', 125, 276022.0, 1],
 ['NY', 126, 277056.0, 1],
 ['NY', 127, 277767.0, 1],
 ['NY', 128, 278414.0, 1],
 ['NY', 129, 278367.0, 1],
 ['NY', 130, 277805.0, 1],
 ['NY', 131, 276254.0, 1],
 ['NY', 132, 274751.0, 1],
 ['NY', 133, 273003.0, 1],
 ['NY', 134, 272211.0, 1],
 ['NY', 135, 272293.0, 1],
 ['NY', 136, 272338.0, 1],
 ['NY', 137, 271767.0, 1],
 ['NY', 138, 270458.0, 1],
 ['NY', 139, 269582.0, 1],
 ['NY', 140, 269230.0, 1],
 ['NY', 141, 268925.0, 1],
 ['NY', 142, 268065.0, 1],
 ['NY', 143, 267338.0, 1],
 ['NY', 144, 267157.0, 1],
 ['NY', 145, 267231.0, 1],
 ['NY', 146, 266686.0, 1],
 ['NY', 147, 265316.0, 1],
 ['NY', 148, 264475.0, 1],
 ['NY', 149, 263855.0, 1],
 ['NY', 150, 263857.0, 1],
 ['NY', 151, 263709.0, 1],
 ['NY', 152, 263964.0, 1],
 ['NY', 153, 263905.0, 1],
 ['NY', 154, 264078.0, 1],
 ['NY', 155, 264164.0, 1],
 ['NY', 156, 264711.0, 1],
 ['NY', 157, 265084.0, 1],
 ['NY', 158, 265869.0, 1],
 ['NY', 159, 267002.0, 1],
 ['NY', 160, 268321.0, 1],
 ['NY', 161, 269519.0, 1],
 ['NY', 162, 270513.0, 1],
 ['NY', 163, 271575.0, 1],
 ['NY', 164, 272525.0, 1],
 ['NY', 165, 273275.0, 1],
 ['NY', 166, 274172.0, 1],
 ['NY', 167, 275331.0, 1],
 ['NY', 168, 276592.0, 1],
 ['NY', 169, 277946.0, 1],
 ['NY', 170, 279595.0, 1],
 ['NY', 171, 281380.0, 1],
 ['NY', 172, 283174.0, 1],
 ['NY', 173, 284471.0, 1],
 ['NY', 174, 285408.0, 1],
 ['NY', 175, 285864.0, 1],
 ['NY', 176, 286925.0, 1],
 ['NY', 177, 288273.0, 1],
 ['NY', 178, 289640.0, 1],
 ['NY', 179, 290541.0, 1],
 ['NY', 180, 291802.0, 1],
 ['NY', 181, 293656.0, 1],
 ['NY', 182, 295384.0, 1],
 ['NY', 183, 296431.0, 1],
 ['NY', 184, 297253.0, 1],
 ['NY', 185, 298151.0, 1],
 ['NY', 186, 299607.0, 1],
 ['NY', 187, 300972.0, 1],
 ['NY', 188, 302312.0, 1],
 ['NY', 189, 303343.0, 1],
 ['NY', 190, 304276.0, 1],
 ['NY', 191, 305679.0, 1],
 ['NY', 192, 306927.0, 1],
 ['NY', 193, 305885.0, 1],
 ['NY', 194, 304446.0, 1],
 ['NY', 195, 303011.0, 1],
 ['NY', 196, 304263.0, 1],
 ['NY', 197, 305531.0, 1],
 ['NY', 198, 306898.0, 1],
 ['NY', 199, 307855.0, 1],
 ['NY', 200, 308503.0, 1],
 ['NY', 201, 308943.0, 1],
 ['NY', 202, 309322.0, 1],
 ['NY', 203, 310055.0, 1],
 ['NY', 204, 311174.0, 1],
 ['NY', 205, 312842.0, 1],
 ['NY', 206, 314185.0, 1],
 ['NY', 207, 315495.0, 1],
 ['NY', 208, 316716.0, 1],
 ['NY', 209, 318701.0, 1],
 ['NY', 210, 320804.0, 1],
 ['NY', 211, 322782.0, 1],
 ['NY', 212, 324392.0, 1],
 ['NY', 213, 326258.0, 1],
 ['NY', 214, 328125.0, 1],
 ['NY', 215, 329986.0, 1],
 ['NY', 216, 331469.0, 1],
 ['NY', 217, 333227.0, 1],
 ['NY', 218, 335141.0, 1],
 ['NY', 219, 337245.0, 1],
 ['NY', 220, 339074.0, 1],
 ['NY', 221, 341039.0, 1],
 ['NY', 222, 342247.0, 1],

In [107]:
for row in dataset:
    row.append(row.pop(0))

dataset

[[1.0, 130666.0, 1.0, 'CA'],
 [2.0, 131262.0, 1.0, 'CA'],
 [3.0, 132034.0, 1.0, 'CA'],
 [4.0, 133738.0, 1.0, 'CA'],
 [5.0, 135643.0, 1.0, 'CA'],
 [6.0, 137697.0, 1.0, 'CA'],
 [7.0, 139782.0, 1.0, 'CA'],
 [8.0, 141994.0, 1.0, 'CA'],
 [9.0, 144212.0, 1.0, 'CA'],
 [10.0, 146304.0, 1.0, 'CA'],
 [11.0, 148353.0, 1.0, 'CA'],
 [12.0, 150391.0, 1.0, 'CA'],
 [13.0, 152079.0, 1.0, 'CA'],
 [14.0, 153868.0, 1.0, 'CA'],
 [15.0, 155928.0, 1.0, 'CA'],
 [16.0, 158424.0, 1.0, 'CA'],
 [17.0, 160714.0, 1.0, 'CA'],
 [18.0, 162704.0, 1.0, 'CA'],
 [19.0, 164631.0, 1.0, 'CA'],
 [20.0, 166603.0, 1.0, 'CA'],
 [21.0, 168431.0, 1.0, 'CA'],
 [22.0, 170128.0, 1.0, 'CA'],
 [23.0, 171705.0, 1.0, 'CA'],
 [24.0, 173142.0, 1.0, 'CA'],
 [25.0, 174344.0, 1.0, 'CA'],
 [26.0, 175640.0, 1.0, 'CA'],
 [27.0, 177241.0, 1.0, 'CA'],
 [28.0, 179312.0, 1.0, 'CA'],
 [29.0, 181614.0, 1.0, 'CA'],
 [30.0, 184119.0, 1.0, 'CA'],
 [31.0, 187082.0, 1.0, 'CA'],
 [32.0, 190201.0, 1.0, 'CA'],
 [33.0, 193263.0, 1.0, 'CA'],
 [34.0, 196075.0, 1.0, 'CA'],
 [35.0, 198869.0, 1.0, 'CA'],
 [36.0, 201715.0, 1.0, 'CA'],
 [37.0, 204124.0, 1.0, 'CA'],
 [38.0, 206381.0, 1.0, 'CA'],
 [39.0, 208869.0, 1.0, 'CA'],
 [40.0, 211691.0, 1.0, 'CA'],
 [41.0, 214729.0, 1.0, 'CA'],
 [42.0, 217272.0, 1.0, 'CA'],
 [43.0, 220254.0, 1.0, 'CA'],
 [44.0, 223411.0, 1.0, 'CA'],
 [45.0, 226923.0, 1.0, 'CA'],
 [46.0, 230104.0, 1.0, 'CA'],
 [47.0, 233209.0, 1.0, 'CA'],
 [48.0, 236203.0, 1.0, 'CA'],
 [49.0, 239746.0, 1.0, 'CA'],
 [50.0, 243813.0, 1.0, 'CA'],
 [51.0, 248495.0, 1.0, 'CA'],
 [52.0, 253490.0, 1.0, 'CA'],
 [53.0, 259276.0, 1.0, 'CA'],
 [54.0, 265740.0, 1.0, 'CA'],
 [55.0, 272035.0, 1.0, 'CA'],
 [56.0, 277665.0, 1.0, 'CA'],
 [57.0, 282896.0, 1.0, 'CA'],
 [58.0, 288025.0, 1.0, 'CA'],
 [59.0, 292408.0, 1.0, 'CA'],
 [60.0, 296945.0, 1.0, 'CA'],
 [61.0, 300921.0, 1.0, 'CA'],
 [62.0, 305457.0, 1.0, 'CA'],
 [63.0, 310271.0, 1.0, 'CA'],
 [64.0, 315769.0, 1.0, 'CA'],
 [65.0, 320979.0, 1.0, 'CA'],
 [66.0, 325538.0, 1.0, 'CA'],
 [67.0, 329939.0, 1.0, 'CA'],
 [68.0, 334524.0, 1.0, 'CA'],
 [69.0, 338938.0, 1.0, 'CA'],
 [70.0, 343312.0, 1.0, 'CA'],
 [71.0, 346475.0, 1.0, 'CA'],
 [72.0, 349550.0, 1.0, 'CA'],
 [73.0, 352081.0, 1.0, 'CA'],
 [74.0, 354487.0, 1.0, 'CA'],
 [75.0, 356691.0, 1.0, 'CA'],
 [76.0, 358422.0, 1.0, 'CA'],
 [77.0, 360133.0, 1.0, 'CA'],
 [78.0, 361026.0, 1.0, 'CA'],
 [79.0, 360894.0, 1.0, 'CA'],
 [80.0, 360482.0, 1.0, 'CA'],
 [81.0, 359103.0, 1.0, 'CA'],
 [82.0, 358162.0, 1.0, 'CA'],
 [83.0, 357112.0, 1.0, 'CA'],
 [84.0, 356490.0, 1.0, 'CA'],
 [85.0, 356124.0, 1.0, 'CA'],
 [86.0, 355586.0, 1.0, 'CA'],
 [87.0, 354637.0, 1.0, 'CA'],
 [88.0, 353212.0, 1.0, 'CA'],
 [89.0, 350882.0, 1.0, 'CA'],
 [90.0, 348425.0, 1.0, 'CA'],
 [91.0, 345180.0, 1.0, 'CA'],
 [92.0, 342072.0, 1.0, 'CA'],
 [93.0, 338515.0, 1.0, 'CA'],
 [94.0, 334662.0, 1.0, 'CA'],
 [95.0, 331214.0, 1.0, 'CA'],
 [96.0, 327157.0, 1.0, 'CA'],
 [97.0, 323655.0, 1.0, 'CA'],
 [98.0, 319064.0, 1.0, 'CA'],
 [99.0, 313719.0, 1.0, 'CA'],
 [100.0, 307614.0, 1.0, 'CA'],
 [101.0, 301029.0, 1.0, 'CA'],
 [102.0, 295113.0, 1.0, 'CA'],
 [103.0, 288829.0, 1.0, 'CA'],
 [104.0, 283002.0, 1.0, 'CA'],
 [105.0, 277239.0, 1.0, 'CA'],
 [106.0, 271753.0, 1.0, 'CA'],
 [107.0, 265721.0, 1.0, 'CA'],
 [108.0, 259991.0, 1.0, 'CA'],
 [109.0, 255011.0, 1.0, 'CA'],
 [110.0, 251742.0, 1.0, 'CA'],
 [111.0, 248435.0, 1.0, 'CA'],
 [112.0, 244487.0, 1.0, 'CA'],
 [113.0, 240709.0, 1.0, 'CA'],
 [114.0, 236902.0, 1.0, 'CA'],
 [115.0, 234089.0, 1.0, 'CA'],
 [116.0, 231488.0, 1.0, 'CA'],
 [117.0, 229853.0, 1.0, 'CA'],
 [118.0, 228985.0, 1.0, 'CA'],
 [119.0, 229426.0, 1.0, 'CA'],
 [120.0, 230888.0, 1.0, 'CA'],
 [121.0, 231305.0, 1.0, 'CA'],
 [122.0, 230685.0, 1.0, 'CA'],
 [123.0, 230107.0, 1.0, 'CA'],
 [124.0, 230207.0, 1.0, 'CA'],
 [125.0, 230248.0, 1.0, 'CA'],
 [126.0, 228532.0, 1.0, 'CA'],
 [127.0, 226233.0, 1.0, 'CA'],
 [128.0, 223494.0, 1.0, 'CA'],
 [129.0, 221063.0, 1.0, 'CA'],
 [130.0, 218644.0, 1.0, 'CA'],
 [131.0, 216246.0, 1.0, 'CA'],
 [132.0, 214557.0, 1.0, 'CA'],
 [133.0, 213035.0, 1.0, 'CA'],
 [134.0, 211867.0, 1.0, 'CA'],
 [135.0, 210195.0, 1.0, 'CA'],
 [136.0, 208474.0, 1.0, 'CA'],
 [137.0, 205885.0, 1.0, 'CA'],
 [138.0, 204175.0, 1.0, 'CA'],
 [139.0, 202649.0, 1.0, 'CA'],
 [140.0, 200740.0, 1.0, 'CA'],
 [141.0, 198535.0, 1.0, 'CA'],
 [142.0, 196427.0, 1.0, 'CA'],
 [143.0, 195827.0, 1.0, 'CA'],
 [144.0, 195302.0, 1.0, 'CA'],
 [145.0, 194891.0, 1.0, 'CA'],
 [146.0, 194445.0, 1.0, 'CA'],
 [147.0, 194303.0, 1.0, 'CA'],
 [148.0, 194787.0, 1.0, 'CA'],
 [149.0, 195871.0, 1.0, 'CA'],
 [150.0, 197371.0, 1.0, 'CA'],
 [151.0, 198978.0, 1.0, 'CA'],
 [152.0, 200607.0, 1.0, 'CA'],
 [153.0, 202356.0, 1.0, 'CA'],
 [154.0, 204888.0, 1.0, 'CA'],
 [155.0, 207873.0, 1.0, 'CA'],
 [156.0, 211873.0, 1.0, 'CA'],
 [157.0, 216120.0, 1.0, 'CA'],
 [158.0, 220780.0, 1.0, 'CA'],
 [159.0, 225870.0, 1.0, 'CA'],
 [160.0, 231461.0, 1.0, 'CA'],
 [161.0, 237234.0, 1.0, 'CA'],
 [162.0, 243201.0, 1.0, 'CA'],
 [163.0, 248757.0, 1.0, 'CA'],
 [164.0, 254066.0, 1.0, 'CA'],
 [165.0, 258691.0, 1.0, 'CA'],
 [166.0, 262863.0, 1.0, 'CA'],
 [167.0, 266997.0, 1.0, 'CA'],
 [168.0, 270901.0, 1.0, 'CA'],
 [169.0, 274738.0, 1.0, 'CA'],
 [170.0, 278193.0, 1.0, 'CA'],
 [171.0, 280231.0, 1.0, 'CA'],
 [172.0, 281509.0, 1.0, 'CA'],
 [173.0, 282185.0, 1.0, 'CA'],
 [174.0, 282985.0, 1.0, 'CA'],
 [175.0, 283806.0, 1.0, 'CA'],
 [176.0, 283648.0, 1.0, 'CA'],
 [177.0, 284148.0, 1.0, 'CA'],
 [178.0, 285261.0, 1.0, 'CA'],
 [179.0, 287748.0, 1.0, 'CA'],
 [180.0, 290001.0, 1.0, 'CA'],
 [181.0, 292077.0, 1.0, 'CA'],
 [182.0, 294230.0, 1.0, 'CA'],
 [183.0, 296897.0, 1.0, 'CA'],
 [184.0, 298971.0, 1.0, 'CA'],
 [185.0, 301161.0, 1.0, 'CA'],
 [186.0, 302746.0, 1.0, 'CA'],
 [187.0, 303568.0, 1.0, 'CA'],
 [188.0, 304793.0, 1.0, 'CA'],
 [189.0, 306783.0, 1.0, 'CA'],
 [190.0, 310004.0, 1.0, 'CA'],
 [191.0, 312668.0, 1.0, 'CA'],
 [192.0, 316050.0, 1.0, 'CA'],
 [193.0, 319429.0, 1.0, 'CA'],
 [194.0, 322472.0, 1.0, 'CA'],
 [195.0, 324006.0, 1.0, 'CA'],
 [196.0, 325831.0, 1.0, 'CA'],
 [197.0, 327507.0, 1.0, 'CA'],
 [198.0, 329483.0, 1.0, 'CA'],
 [199.0, 329927.0, 1.0, 'CA'],
 [200.0, 331256.0, 1.0, 'CA'],
 [201.0, 332721.0, 1.0, 'CA'],
 [202.0, 335865.0, 1.0, 'CA'],
 [203.0, 338422.0, 1.0, 'CA'],
 [204.0, 340570.0, 1.0, 'CA'],
 [205.0, 342790.0, 1.0, 'CA'],
 [206.0, 344974.0, 1.0, 'CA'],
 [207.0, 347385.0, 1.0, 'CA'],
 [208.0, 349299.0, 1.0, 'CA'],
 [209.0, 351767.0, 1.0, 'CA'],
 [210.0, 354584.0, 1.0, 'CA'],
 [211.0, 356140.0, 1.0, 'CA'],
 [212.0, 357715.0, 1.0, 'CA'],
 [213.0, 359848.0, 1.0, 'CA'],
 [214.0, 363372.0, 1.0, 'CA'],
 [215.0, 367175.0, 1.0, 'CA'],
 [216.0, 370750.0, 1.0, 'CA'],
 [217.0, 374694.0, 1.0, 'CA'],
 [218.0, 378774.0, 1.0, 'CA'],
 [219.0, 382552.0, 1.0, 'CA'],
 [220.0, 385701.0, 1.0, 'CA'],
 [221.0, 388141.0, 1.0, 'CA'],
 [222.0, 390685.0, 1.0, 'CA'],
 [223.0, 392075.0, 1.0, 'CA'],
 [224.0, 393482.0, 1.0, 'CA'],
 [225.0, 394213.0, 1.0, 'CA'],
 [226.0, 395853.0, 1.0, 'CA'],
 [227.0, 396758.0, 1.0, 'CA'],
 [228.0, 396507.0, 1.0, 'CA'],
 [229.0, 395789.0, 1.0, 'CA'],
 [230.0, 395068.0, 1.0, 'CA'],
 [231.0, 394791.0, 1.0, 'CA'],
 [232.0, 395127.0, 1.0, 'CA'],
 [233.0, 395495.0, 1.0, 'CA'],
 [234.0, 395922.0, 1.0, 'CA'],
 [235.0, 395532.0, 1.0, 'CA'],
 [236.0, 395472.0, 1.0, 'CA'],
 [237.0, 395952.0, 1.0, 'CA'],
 [238.0, 397162.0, 1.0, 'CA'],
 [239.0, 398034.0, 1.0, 'CA'],
 [240.0, 399372.0, 1.0, 'CA'],
 [241.0, 401491.0, 1.0, 'CA'],
 [242.0, 404459.0, 1.0, 'CA'],
 [243.0, 407536.0, 1.0, 'CA'],
 [244.0, 409356.0, 1.0, 'CA'],
 [245.0, 408019.0, 1.0, 'CA'],
 [246.0, 406206.0, 1.0, 'CA'],
 [247.0, 406824.0, 1.0, 'CA'],
 [248.0, 410979.0, 1.0, 'CA'],
 [249.0, 415552.0, 1.0, 'CA'],
 [250.0, 419633.0, 1.0, 'CA'],
 [251.0, 423086.0, 1.0, 'CA'],
 [252.0, 426065.0, 1.0, 'CA'],
 [253.0, 428636.0, 1.0, 'CA'],
 [254.0, 431844.0, 1.0, 'CA'],
 [255.0, 435629.0, 1.0, 'CA'],
 [256.0, 440640.0, 1.0, 'CA'],
 [257.0, 448266.0, 1.0, 'CA'],
 [258.0, 457786.0, 1.0, 'CA'],
 [259.0, 467937.0, 1.0, 'CA'],
 [260.0, 474558.0, 1.0, 'CA'],
 [261.0, 478763.0, 1.0, 'CA'],
 [262.0, 480599.0, 1.0, 'CA'],
 [263.0, 483470.0, 1.0, 'CA'],
 [264.0, 487631.0, 1.0, 'CA'],
 [265.0, 493892.0, 1.0, 'CA'],
 [266.0, 501094.0, 1.0, 'CA'],
 [267.0, 510219.0, 1.0, 'CA'],
 [268.0, 518854.0, 1.0, 'CA'],
 [269.0, 525553.0, 1.0, 'CA'],
 [1.0, 79217.0, 1.0, 'TX'],
 [2.0, 79404.0, 1.0, 'TX'],
 [3.0, 79462.0, 1.0, 'TX'],
 [4.0, 79387.0, 1.0, 'TX'],
 [5.0, 79256.0, 1.0, 'TX'],
 [6.0, 78960.0, 1.0, 'TX'],
 [7.0, 79271.0, 1.0, 'TX'],
 [8.0, 79487.0, 1.0, 'TX'],
 [9.0, 79837.0, 1.0, 'TX'],
 [10.0, 79867.0, 1.0, 'TX'],
 [11.0, 80180.0, 1.0, 'TX'],
 [12.0, 80665.0, 1.0, 'TX'],
 [13.0, 81011.0, 1.0, 'TX'],
 [14.0, 80965.0, 1.0, 'TX'],
 [15.0, 80694.0, 1.0, 'TX'],
 [16.0, 80655.0, 1.0, 'TX'],
 [17.0, 80624.0, 1.0, 'TX'],
 [18.0, 80625.0, 1.0, 'TX'],
 [19.0, 80393.0, 1.0, 'TX'],
 [20.0, 80253.0, 1.0, 'TX'],
 [21.0, 80145.0, 1.0, 'TX'],
 [22.0, 80347.0, 1.0, 'TX'],
 [23.0, 80209.0, 1.0, 'TX'],
 [24.0, 80177.0, 1.0, 'TX'],
 [25.0, 79638.0, 1.0, 'TX'],
 [26.0, 79674.0, 1.0, 'TX'],
 [27.0, 79301.0, 1.0, 'TX'],
 [28.0, 79544.0, 1.0, 'TX'],
 [29.0, 79562.0, 1.0, 'TX'],
 [30.0, 80006.0, 1.0, 'TX'],
 [31.0, 80373.0, 1.0, 'TX'],
 [32.0, 80705.0, 1.0, 'TX'],
 [33.0, 80797.0, 1.0, 'TX'],
 [34.0, 80689.0, 1.0, 'TX'],
 [35.0, 81055.0, 1.0, 'TX'],
 [36.0, 81134.0, 1.0, 'TX'],
 [37.0, 81408.0, 1.0, 'TX'],
 [38.0, 81259.0, 1.0, 'TX'],
 [39.0, 81707.0, 1.0, 'TX'],
 [40.0, 81352.0, 1.0, 'TX'],
 [41.0, 80891.0, 1.0, 'TX'],
 [42.0, 80433.0, 1.0, 'TX'],
 [43.0, 80014.0, 1.0, 'TX'],
 [44.0, 80105.0, 1.0, 'TX'],
 [45.0, 79948.0, 1.0, 'TX'],
 [46.0, 79957.0, 1.0, 'TX'],
 [47.0, 79801.0, 1.0, 'TX'],
 [48.0, 79961.0, 1.0, 'TX'],
 [49.0, 80586.0, 1.0, 'TX'],
 [50.0, 80821.0, 1.0, 'TX'],
 [51.0, 81635.0, 1.0, 'TX'],
 [52.0, 82065.0, 1.0, 'TX'],
 [53.0, 83022.0, 1.0, 'TX'],
 [54.0, 82927.0, 1.0, 'TX'],
 [55.0, 82832.0, 1.0, 'TX'],
 [56.0, 82835.0, 1.0, 'TX'],
 [57.0, 83068.0, 1.0, 'TX'],
 [58.0, 83397.0, 1.0, 'TX'],
 [59.0, 83072.0, 1.0, 'TX'],
 [60.0, 83123.0, 1.0, 'TX'],
 [61.0, 83594.0, 1.0, 'TX'],
 [62.0, 83973.0, 1.0, 'TX'],
 [63.0, 84235.0, 1.0, 'TX'],
 [64.0, 84142.0, 1.0, 'TX'],
 [65.0, 84416.0, 1.0, 'TX'],
 [66.0, 83974.0, 1.0, 'TX'],
 [67.0, 83873.0, 1.0, 'TX'],
 [68.0, 83794.0, 1.0, 'TX'],
 [69.0, 84368.0, 1.0, 'TX'],
 [70.0, 84333.0, 1.0, 'TX'],
 [71.0, 84369.0, 1.0, 'TX'],
 [72.0, 84491.0, 1.0, 'TX'],
 [73.0, 84902.0, 1.0, 'TX'],
 [74.0, 85208.0, 1.0, 'TX'],
 [75.0, 84977.0, 1.0, 'TX'],
 [76.0, 85023.0, 1.0, 'TX'],
 [77.0, 85423.0, 1.0, 'TX'],
 [78.0, 85779.0, 1.0, 'TX'],
 [79.0, 85977.0, 1.0, 'TX'],
 [80.0, 85646.0, 1.0, 'TX'],
 [81.0, 86203.0, 1.0, 'TX'],
 [82.0, 86199.0, 1.0, 'TX'],
 [83.0, 86524.0, 1.0, 'TX'],
 [84.0, 86179.0, 1.0, 'TX'],
 [85.0, 86303.0, 1.0, 'TX'],
 [86.0, 85826.0, 1.0, 'TX'],
 [87.0, 85494.0, 1.0, 'TX'],
 [88.0, 85840.0, 1.0, 'TX'],
 [89.0, 86363.0, 1.0, 'TX'],
 [90.0, 86546.0, 1.0, 'TX'],
 [91.0, 86392.0, 1.0, 'TX'],
 [92.0, 86144.0, 1.0, 'TX'],
 [93.0, 86388.0, 1.0, 'TX'],
 [94.0, 86112.0, 1.0, 'TX'],
 [95.0, 86330.0, 1.0, 'TX'],
 [96.0, 85844.0, 1.0, 'TX'],
 [97.0, 85404.0, 1.0, 'TX'],
 [98.0, 84734.0, 1.0, 'TX'],
 [99.0, 84481.0, 1.0, 'TX'],
 [100.0, 84439.0, 1.0, 'TX'],
 [101.0, 84378.0, 1.0, 'TX'],
 [102.0, 84418.0, 1.0, 'TX'],
 [103.0, 84260.0, 1.0, 'TX'],
 [104.0, 83934.0, 1.0, 'TX'],
 [105.0, 83457.0, 1.0, 'TX'],
 [106.0, 82990.0, 1.0, 'TX'],
 [107.0, 82209.0, 1.0, 'TX'],
 [108.0, 81675.0, 1.0, 'TX'],
 [109.0, 80910.0, 1.0, 'TX'],
 [110.0, 80810.0, 1.0, 'TX'],
 [111.0, 80486.0, 1.0, 'TX'],
 [112.0, 80605.0, 1.0, 'TX'],
 [113.0, 80555.0, 1.0, 'TX'],
 [114.0, 80581.0, 1.0, 'TX'],
 [115.0, 80495.0, 1.0, 'TX'],
 [116.0, 80156.0, 1.0, 'TX'],
 [117.0, 79795.0, 1.0, 'TX'],
 [118.0, 79397.0, 1.0, 'TX'],
 [119.0, 79255.0, 1.0, 'TX'],
 [120.0, 79202.0, 1.0, 'TX'],
 [121.0, 78914.0, 1.0, 'TX'],
 [122.0, 78667.0, 1.0, 'TX'],
 [123.0, 78269.0, 1.0, 'TX'],
 [124.0, 78173.0, 1.0, 'TX'],
 [125.0, 78077.0, 1.0, 'TX'],
 [126.0, 77980.0, 1.0, 'TX'],
 [127.0, 77614.0, 1.0, 'TX'],
 [128.0, 77228.0, 1.0, 'TX'],
 [129.0, 76808.0, 1.0, 'TX'],
 [130.0, 76558.0, 1.0, 'TX'],
 [131.0, 76119.0, 1.0, 'TX'],
 [132.0, 75806.0, 1.0, 'TX'],
 [133.0, 75214.0, 1.0, 'TX'],
 [134.0, 74771.0, 1.0, 'TX'],
 [135.0, 74098.0, 1.0, 'TX'],
 [136.0, 73775.0, 1.0, 'TX'],
 [137.0, 73437.0, 1.0, 'TX'],
 [138.0, 73395.0, 1.0, 'TX'],
 [139.0, 73413.0, 1.0, 'TX'],
 [140.0, 73553.0, 1.0, 'TX'],
 [141.0, 73575.0, 1.0, 'TX'],
 [142.0, 73652.0, 1.0, 'TX'],
 [143.0, 73521.0, 1.0, 'TX'],
 [144.0, 73449.0, 1.0, 'TX'],
 [145.0, 73149.0, 1.0, 'TX'],
 [146.0, 73210.0, 1.0, 'TX'],
 [147.0, 73230.0, 1.0, 'TX'],
 [148.0, 73311.0, 1.0, 'TX'],
 [149.0, 73295.0, 1.0, 'TX'],
 [150.0, 73645.0, 1.0, 'TX'],
 [151.0, 74147.0, 1.0, 'TX'],
 [152.0, 74504.0, 1.0, 'TX'],
 [153.0, 74552.0, 1.0, 'TX'],
 [154.0, 74710.0, 1.0, 'TX'],
 [155.0, 74915.0, 1.0, 'TX'],
 [156.0, 75282.0, 1.0, 'TX'],
 [157.0, 75543.0, 1.0, 'TX'],
 [158.0, 76057.0, 1.0, 'TX'],
 [159.0, 76617.0, 1.0, 'TX'],
 [160.0, 77344.0, 1.0, 'TX'],
 [161.0, 77926.0, 1.0, 'TX'],
 [162.0, 78529.0, 1.0, 'TX'],
 [163.0, 79121.0, 1.0, 'TX'],
 [164.0, 79788.0, 1.0, 'TX'],
 [165.0, 80373.0, 1.0, 'TX'],
 [166.0, 81034.0, 1.0, 'TX'],
 [167.0, 81584.0, 1.0, 'TX'],
 [168.0, 82120.0, 1.0, 'TX'],
 [169.0, 82598.0, 1.0, 'TX'],
 [170.0, 83253.0, 1.0, 'TX'],
 [171.0, 83747.0, 1.0, 'TX'],
 [172.0, 84158.0, 1.0, 'TX'],
 [173.0, 84475.0, 1.0, 'TX'],
 [174.0, 85224.0, 1.0, 'TX'],
 [175.0, 85797.0, 1.0, 'TX'],
 [176.0, 86480.0, 1.0, 'TX'],
 [177.0, 86819.0, 1.0, 'TX'],
 [178.0, 87446.0, 1.0, 'TX'],
 [179.0, 88091.0, 1.0, 'TX'],
 [180.0, 88999.0, 1.0, 'TX'],
 [181.0, 89689.0, 1.0, 'TX'],
 [182.0, 90330.0, 1.0, 'TX'],
 [183.0, 90892.0, 1.0, 'TX'],
 [184.0, 91398.0, 1.0, 'TX'],
 [185.0, 91927.0, 1.0, 'TX'],
 [186.0, 92460.0, 1.0, 'TX'],
 [187.0, 93055.0, 1.0, 'TX'],
 [188.0, 93540.0, 1.0, 'TX'],
 [189.0, 93934.0, 1.0, 'TX'],
 [190.0, 94631.0, 1.0, 'TX'],
 [191.0, 95148.0, 1.0, 'TX'],
 [192.0, 95813.0, 1.0, 'TX'],
 [193.0, 96234.0, 1.0, 'TX'],
 [194.0, 96895.0, 1.0, 'TX'],
 [195.0, 97478.0, 1.0, 'TX'],
 [196.0, 98115.0, 1.0, 'TX'],
 [197.0, 98794.0, 1.0, 'TX'],
 [198.0, 99550.0, 1.0, 'TX'],
 [199.0, 100478.0, 1.0, 'TX'],
 [200.0, 100991.0, 1.0, 'TX'],
 [201.0, 101441.0, 1.0, 'TX'],
 [202.0, 101978.0, 1.0, 'TX'],
 [203.0, 103103.0, 1.0, 'TX'],
 [204.0, 104394.0, 1.0, 'TX'],
 [205.0, 105347.0, 1.0, 'TX'],
 [206.0, 106074.0, 1.0, 'TX'],
 [207.0, 106603.0, 1.0, 'TX'],
 [208.0, 107163.0, 1.0, 'TX'],
 [209.0, 107704.0, 1.0, 'TX'],
 [210.0, 108292.0, 1.0, 'TX'],
 [211.0, 108953.0, 1.0, 'TX'],
 [212.0, 109450.0, 1.0, 'TX'],
 [213.0, 109841.0, 1.0, 'TX'],
 [214.0, 110258.0, 1.0, 'TX'],
 [215.0, 110975.0, 1.0, 'TX'],
 [216.0, 111821.0, 1.0, 'TX'],
 [217.0, 112774.0, 1.0, 'TX'],
 [218.0, 113646.0, 1.0, 'TX'],
 [219.0, 114461.0, 1.0, 'TX'],
 [220.0, 115273.0, 1.0, 'TX'],
 [221.0, 116000.0, 1.0, 'TX'],
 [222.0, 116730.0, 1.0, 'TX'],
 [223.0, 117336.0, 1.0, 'TX'],
 [224.0, 118133.0, 1.0, 'TX'],
 [225.0, 118762.0, 1.0, 'TX'],
 [226.0, 119364.0, 1.0, 'TX'],
 [227.0, 119853.0, 1.0, 'TX'],
 [228.0, 120573.0, 1.0, 'TX'],
 [229.0, 121629.0, 1.0, 'TX'],
 [230.0, 122650.0, 1.0, 'TX'],
 [231.0, 123296.0, 1.0, 'TX'],
 [232.0, 123614.0, 1.0, 'TX'],
 [233.0, 123790.0, 1.0, 'TX'],
 [234.0, 124146.0, 1.0, 'TX'],
 [235.0, 124531.0, 1.0, 'TX'],
 [236.0, 125210.0, 1.0, 'TX'],
 [237.0, 126118.0, 1.0, 'TX'],
 [238.0, 126525.0, 1.0, 'TX'],
 [239.0, 126689.0, 1.0, 'TX'],
 [240.0, 126372.0, 1.0, 'TX'],
 [241.0, 126895.0, 1.0, 'TX'],
 [242.0, 127364.0, 1.0, 'TX'],
 [243.0, 128164.0, 1.0, 'TX'],
 [244.0, 128433.0, 1.0, 'TX'],
 [245.0, 128767.0, 1.0, 'TX'],
 [246.0, 128949.0, 1.0, 'TX'],
 [247.0, 129218.0, 1.0, 'TX'],
 [248.0, 129811.0, 1.0, 'TX'],
 [249.0, 131283.0, 1.0, 'TX'],
 [250.0, 133019.0, 1.0, 'TX'],
 [251.0, 134795.0, 1.0, 'TX'],
 [252.0, 135905.0, 1.0, 'TX'],
 [253.0, 137237.0, 1.0, 'TX'],
 [254.0, 138576.0, 1.0, 'TX'],
 [255.0, 139763.0, 1.0, 'TX'],
 [256.0, 141278.0, 1.0, 'TX'],
 [257.0, 143013.0, 1.0, 'TX'],
 [258.0, 145792.0, 1.0, 'TX'],
 [259.0, 148331.0, 1.0, 'TX'],
 [260.0, 151288.0, 1.0, 'TX'],
 [261.0, 153565.0, 1.0, 'TX'],
 [262.0, 155598.0, 1.0, 'TX'],
 [263.0, 157066.0, 1.0, 'TX'],
 [264.0, 159203.0, 1.0, 'TX'],
 [265.0, 161747.0, 1.0, 'TX'],
 [266.0, 164703.0, 1.0, 'TX'],
 [267.0, 167546.0, 1.0, 'TX'],
 [268.0, 170630.0, 1.0, 'TX'],
 [269.0, 173599.0, 1.0, 'TX'],
 [1.0, 149865.0, 1.0, 'NY'],
 [2.0, 150836.0, 1.0, 'NY'],
 [3.0, 151597.0, 1.0, 'NY'],
 [4.0, 153131.0, 1.0, 'NY'],
 [5.0, 154511.0, 1.0, 'NY'],
 [6.0, 156097.0, 1.0, 'NY'],
 [7.0, 157599.0, 1.0, 'NY'],
 [8.0, 158773.0, 1.0, 'NY'],
 [9.0, 159668.0, 1.0, 'NY'],
 [10.0, 160657.0, 1.0, 'NY'],
 [11.0, 162105.0, 1.0, 'NY'],
 [12.0, 163673.0, 1.0, 'NY'],
 [13.0, 165247.0, 1.0, 'NY'],
 [14.0, 166597.0, 1.0, 'NY'],
 [15.0, 168113.0, 1.0, 'NY'],
 [16.0, 169609.0, 1.0, 'NY'],
 [17.0, 171164.0, 1.0, 'NY'],
 [18.0, 172552.0, 1.0, 'NY'],
 [19.0, 173916.0, 1.0, 'NY'],
 [20.0, 175445.0, 1.0, 'NY'],
 [21.0, 177064.0, 1.0, 'NY'],
 [22.0, 178746.0, 1.0, 'NY'],
 [23.0, 180347.0, 1.0, 'NY'],
 [24.0, 181802.0, 1.0, 'NY'],
 [25.0, 183472.0, 1.0, 'NY'],
 [26.0, 184815.0, 1.0, 'NY'],
 [27.0, 186108.0, 1.0, 'NY'],
 [28.0, 187315.0, 1.0, 'NY'],
 [29.0, 188799.0, 1.0, 'NY'],
 [30.0, 190431.0, 1.0, 'NY'],
 [31.0, 192007.0, 1.0, 'NY'],
 [32.0, 193752.0, 1.0, 'NY'],
 [33.0, 195534.0, 1.0, 'NY'],
 [34.0, 197267.0, 1.0, 'NY'],
 [35.0, 199017.0, 1.0, 'NY'],
 [36.0, 200838.0, 1.0, 'NY'],
 [37.0, 202886.0, 1.0, 'NY'],
 [38.0, 204961.0, 1.0, 'NY'],
 [39.0, 207494.0, 1.0, 'NY'],
 [40.0, 209552.0, 1.0, 'NY'],
 [41.0, 211848.0, 1.0, 'NY'],
 [42.0, 214336.0, 1.0, 'NY'],
 [43.0, 217077.0, 1.0, 'NY'],
 [44.0, 219904.0, 1.0, 'NY'],
 [45.0, 222178.0, 1.0, 'NY'],
 [46.0, 224588.0, 1.0, 'NY'],
 [47.0, 226471.0, 1.0, 'NY'],
 [48.0, 228381.0, 1.0, 'NY'],
 [49.0, 230369.0, 1.0, 'NY'],
 [50.0, 232363.0, 1.0, 'NY'],
 [51.0, 234281.0, 1.0, 'NY'],
 [52.0, 236276.0, 1.0, 'NY'],
 [53.0, 238749.0, 1.0, 'NY'],
 [54.0, 241592.0, 1.0, 'NY'],
 [55.0, 244639.0, 1.0, 'NY'],
 [56.0, 247537.0, 1.0, 'NY'],
 [57.0, 250793.0, 1.0, 'NY'],
 [58.0, 253952.0, 1.0, 'NY'],
 [59.0, 257222.0, 1.0, 'NY'],
 [60.0, 260152.0, 1.0, 'NY'],
 [61.0, 263301.0, 1.0, 'NY'],
 [62.0, 266414.0, 1.0, 'NY'],
 [63.0, 269567.0, 1.0, 'NY'],
 [64.0, 272776.0, 1.0, 'NY'],
 [65.0, 276104.0, 1.0, 'NY'],
 [66.0, 279216.0, 1.0, 'NY'],
 [67.0, 282263.0, 1.0, 'NY'],
 [68.0, 285559.0, 1.0, 'NY'],
 [69.0, 288790.0, 1.0, 'NY'],
 [70.0, 292469.0, 1.0, 'NY'],
 [71.0, 295736.0, 1.0, 'NY'],
 [72.0, 299356.0, 1.0, 'NY'],
 [73.0, 302448.0, 1.0, 'NY'],
 [74.0, 305077.0, 1.0, 'NY'],
 [75.0, 306876.0, 1.0, 'NY'],
 [76.0, 308288.0, 1.0, 'NY'],
 [77.0, 309948.0, 1.0, 'NY'],
 [78.0, 311478.0, 1.0, 'NY'],
 [79.0, 312466.0, 1.0, 'NY'],
 [80.0, 312731.0, 1.0, 'NY'],
 [81.0, 312709.0, 1.0, 'NY'],
 [82.0, 312443.0, 1.0, 'NY'],
 [83.0, 312281.0, 1.0, 'NY'],
 [84.0, 312489.0, 1.0, 'NY'],
 [85.0, 312345.0, 1.0, 'NY'],
 [86.0, 312318.0, 1.0, 'NY'],
 [87.0, 312643.0, 1.0, 'NY'],
 [88.0, 313180.0, 1.0, 'NY'],
 [89.0, 313874.0, 1.0, 'NY'],
 [90.0, 313566.0, 1.0, 'NY'],
 [91.0, 313241.0, 1.0, 'NY'],
 [92.0, 312944.0, 1.0, 'NY'],
 [93.0, 313061.0, 1.0, 'NY'],
 [94.0, 313678.0, 1.0, 'NY'],
 [95.0, 314015.0, 1.0, 'NY'],
 [96.0, 313998.0, 1.0, 'NY'],
 [97.0, 313971.0, 1.0, 'NY'],
 [98.0, 313732.0, 1.0, 'NY'],
 [99.0, 313499.0, 1.0, 'NY'],
 [100.0, 313035.0, 1.0, 'NY'],
 [101.0, 312201.0, 1.0, 'NY'],
 [102.0, 311051.0, 1.0, 'NY'],
 [103.0, 309579.0, 1.0, 'NY'],
 [104.0, 308502.0, 1.0, 'NY'],
 [105.0, 307319.0, 1.0, 'NY'],
 [106.0, 305737.0, 1.0, 'NY'],
 [107.0, 303467.0, 1.0, 'NY'],
 [108.0, 300601.0, 1.0, 'NY'],
 [109.0, 296506.0, 1.0, 'NY'],
 [110.0, 292729.0, 1.0, 'NY'],
 [111.0, 289571.0, 1.0, 'NY'],
 [112.0, 287146.0, 1.0, 'NY'],
 [113.0, 285431.0, 1.0, 'NY'],
 [114.0, 283252.0, 1.0, 'NY'],
 [115.0, 281379.0, 1.0, 'NY'],
 [116.0, 278718.0, 1.0, 'NY'],
 [117.0, 277014.0, 1.0, 'NY'],
 [118.0, 276291.0, 1.0, 'NY'],
 [119.0, 276011.0, 1.0, 'NY'],
 [120.0, 275230.0, 1.0, 'NY'],
 [121.0, 275091.0, 1.0, 'NY'],
 [122.0, 275582.0, 1.0, 'NY'],
 [123.0, 275899.0, 1.0, 'NY'],
 [124.0, 276170.0, 1.0, 'NY'],

In [100]:
print('Train: ' + repr(len(training_set)))
print('Test: ' + repr(len(testing_set)))

Train: 154132
Test: 8044

# KNN Model

In [83]:
import math

def euclidean_distance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]), 2)
    return math.sqrt(distance)

In [84]:
import operator

def get_neighbors(training_set, test_instance, k):
    distances = []
    length = len(test_instance) - 1
    for x in range(len(training_set)):
        dist = euclidean_distance(test_instance, training_set[x], length)
        distances.append((training_set[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

In [85]:
import operator

def get_response(neighbors):
    class_votes = {}
    for x in range(len(neighbors)):
        response = neighbors[x][-1]
        if response in class_votes:
            class_votes[response] += 1
        else:
            class_votes[response] = 1
    sorted_votes = sorted(class_votes.items(), key=operator.itemgetter(1), reverse=True)
    return sorted_votes[0][0]

In [86]:
def get_accuracy(test_set, predictions): 
    correct = 0
    for x in range(len(test_set)):
        if test_set[x][-1] == predictions[x]:
            correct += 1
    print(correct)
    return (correct / float(len(test_set))) * 100.0

In [115]:
import random

def deploy_model(dataset, split, k):
    # split into train and test
    training_set = []
    testing_set = []
    for x in range(len(dataset)):
        for y in range(3):
            dataset[x][y] = float(dataset[x][y])
        if random.random() < split:
            training_set.append(dataset[x])
        else: 
            testing_set.append(dataset[x])
    # generate predictions
    predictions = []
    for x in range(len(testing_set)):
        neighbors = get_neighbors(training_set, testing_set[x], k)
        result = get_response(neighbors)
        predictions.append(result)
#         print('> predicted=' + repr(result) + ', actual=' + repr(testing_set[x][-1]))
    accuracy = get_accuracy(testing_set, predictions)
    return accuracy
#     print('Accuracy: ' + repr(accuracy) + '%')

In [116]:
dfk = pd.DataFrame(columns=['K', 'Split', 'Accuracy'])
dfk.head()

Empty DataFrame
Columns: [K, Split, Accuracy]
Index: []

In [ ]:
split = 0.9
for k_value in range(1,3000):
    accuracy = deploy_model(dataset, split, k_value)
    dfk = dfk.append({'K-Value': k_value, 'Split' : split, 'Accuracy' : accuracy}, ignore_index=True)

dfk

15088